### ISSUE TITLE
SPORE data dictionary expansion notes

### ISSUE THREAD

**Issue by allaway** [nf-osi/nf-metadata-dictionary#109]
I didn't file separate issues because it was a little difficult to keep up with the talks and take these notes at the same time: 
* `platform` = Chromium (single cell platform)
* `assay` = spatial transcriptomics - `platform` = 10X Visium  and/or Nanostring GeoMX (these might require their own dataType and metadata template because its a combination of seq and histology)
* Massively Parallel Reporter Assay (MPRA)

**Comment by anngvu** [comment]
Since assay terms have been added and template task is in #160, I will close this.
