### ISSUE TITLE
Maintain data model as more modular files

### ISSUE THREAD

**Issue by anngvu** [nf-osi/nf-metadata-dictionary#119]
With conversion of .csv to .jsonld via CI introduced in https://github.com/nf-osi/nf-metadata-dictionary/pull/113, I was thinking that we can add an additional CI step and working structure. One of the things I dislike about the current .csv is having to make sure terms are inserted in the correct "block" manually. **And for a new contributor, being presented with the full .csv could be overwhelming.** 

We can potentially split the .csv up into the different components so that you have `assay.csv`, `tumor.csv`, etc., and the flow would look more like below. If someone knows that they are just going to add a bunch of new tumors or model systems, they can go straight to that module. Also, it can be clearer what was changed because it's reflected in specific file changes.

```mermaid
graph LR
    A("Add new tumor to<br/>modules/tumor.csv") -->|concat-script| B(NF.csv)
    B -->|schematic-convert| C(NF.jsonld)
```

**Comment by allaway** [comment]
Ah, that's an interesting idea! I'd be in support of this. At the same time, should we reformat the csv(s) so that we are better using the "Components" concept?
