### ISSUE TITLE
add key: aliquot ID AND parentSpecimenID

### ISSUE THREAD

**Issue by allaway** [nf-osi/nf-metadata-dictionary#125]
**List the new key**
aliquotID

**Provide definition and source for the new key**
Definition:  A unique identifier assigned to an aliquot containing a portion of a biospecimen. [ NCI ]
Source url: http://purl.obolibrary.org/obo/NCIT_C173074

**Please describe why this concept is necessary**
This can be useful in keeping track of the provenance of physical specimens, where individualID == the patient, specimenID == tumor or normal sample, aliquotID == an ID representing the sample of the specimenID (e.g. `patient 1 tumor 1 RNA #1`). 

**Please describe the situations in which this concept may apply**
This could be necessary in situations where different aliquots exist and sequencing was repeated (e.g. technical replicates).

**Comment by jaybee84** [comment]
I was thinking a bit about this after our discussion at standup. Below are some use cases:

Scenario 1:
Tumor A taken from Patient 1, sequenced with 3 technical replicates 
IndividualID = 1
specimenID = A
aliquotID = DNA-1, DNA-2, DNA-3
FileID = 1,2,3
assay = WGS

Scenario 2:
Tumor A taken from Patient 1, made into a cell line, 2 biological replicates alpha, beta, sequenced with 2 technical replicates from each biological replicate
IndividualID = 1
specimenID = A
aliquotID = DNA-1, DNA-2, DNA-3, DNA-4
FileID = 1,2,3,4
assay = WGS

If we use `parentBioSpecimenID`, the annotations look like this:
IndividualID = 1
parentBioSpecimenID = A
specimenID = alpha, beta
aliquotID = DNA-1, DNA-2, DNA-3, DNA-4
FileID = 1,2,3,4
assay = WGS

Scenario 3:
Tumor A taken from Patient 1, made into a cell line, 2 biological replicates alpha, beta, sequenced with 2 technical replicates from aliquots from each biological replicate, sequenced for both RNA and DNA
IndividualID = 1
specimenID = A
aliquotID = RNA-1,RNA-2, RNA-3, RNA-4, DNA-1, DNA-2, DNA-3, DNA-4
FileID = 1,2,3,4,5,6,7,8
assay = WGS, RNAseq

If we use `parentBioSpecimenID`, the annotations look like this:
IndividualID = 1
parentBioSpecimenID = A
specimenID = alpha, beta
aliquotID = RNA-1,RNA-2, RNA-3, RNA-4, DNA-1, DNA-2, DNA-3, DNA-4
FileID = 1,2,3,4,5,6,7,8
assay = WGS, RNAseq

Scenario 4:
Tumor A taken from Patient 1, sequenced with 2 technical replicates from aliquots from each biological replicate, sequenced for both RNA and DNA. 
Tumor B taken from Patient 1, sequenced with 2 technical replicates from aliquots from each biological replicate, sequenced for both RNA and DNA. 

IndividualID = 1
specimenID = A,B
aliquotID = RNA-1,RNA-2, RNA-3, RNA-4, DNA-1, DNA-2, DNA-3, DNA-4
FileID = 1,2,3,4,5,6,7,8
assay = WGS, RNAseq

Usability:
From a computational user:
Query:
`select * from table where individualID ==1 AND assay == WGS AND specimenID == A`
Result :
`aliquotID = DNA-1, DNA-2`
`FileID = 5,6`

From a non-computational user:
Query:
`select * from table where individualID ==1 AND specimenID == A`
Result :
`aliquotID = DNA-1, DNA-2, RNA-1, RNA-2`
`FileID = 1,2,5,6`

**If we use `parentBioSpecimenID`, the annotations look like this:**
IndividualID = 1
parentBioSpecimenID = A, B
specimenID = A-1, A-2, B-1, B-2
aliquotID = RNA-1, RNA-2, RNA-3, RNA-4, DNA-1, DNA-2, DNA-3, DNA-4
FileID = 1,2,3,4,5,6,7,8
assay = WGS, RNAseq

From a computational user:
Query 1:
`select * from table where individualID ==1 AND assay == WGS AND specimenID == A-1`
Result :
`aliquotID = DNA-1, DNA-2`
`FileID = 5,6`

Query 2:
`select * from table where individualID ==1 AND assay == WGS AND parentBioSpecimenID == A`
Result :
`aliquotID = DNA-1, DNA-2`
`FileID = 5,6`

From a non-computational user: 
Query:
`select * from table where individualID ==1 AND specimenID == A-1`
Result :
`aliquotID = DNA-1, DNA-2, RNA-1, RNA-2`
`FileID = 1, 2, 5,6`

**Comment by jaybee84** [comment]
From the above long train of thought, I am leaning towards adding both `aliquotID` and `parentBioSpecimenID` to adequately capture sample provenance. 

In the column definition we should clarify that if each specimen is sequenced only once, the `aliquotID` == `specimenID`
