### ISSUE TITLE
consortium

### ISSUE THREAD

**Issue by anngvu** [nf-osi/nf-metadata-dictionary#13]
This concept is currently being used out in the wild but is not found in the schema. It seems sufficiently useful, and no term of same meaning already exists in schema. 

Recommendation: add concept to schema

**Comment by allaway** [comment]
(Same comment as #46 )

**Comment by cconrad8** [comment]
closing this ticket as consortium is equivalent to fundingAgency 

https://github.com/nf-osi/nf-metadata-dictionary/blob/b86e50279d0a745f1d2e49a82131c358d8978ee8/modules/Template/PortalDataset.yaml#L68

initiative is also added here: https://github.com/nf-osi/nf-metadata-dictionary/blob/b86e50279d0a745f1d2e49a82131c358d8978ee8/modules/props.yaml#L511

**Comment by allaway** [comment]
## Curation Review — NADIA Agent

**Synapse Project:** [syn74273259](https://www.synapse.org/#!Synapse:syn74273259)
**Source:** GEO:GSE301187
**PMID:** [41760889](https://pubmed.ncbi.nlm.nih.gov/41760889/)
**DOI:** 10.1038/s41698-026-01303-6

### Changes Applied

**Publication:** *Pembrolizumab in advanced malignant peripheral nerve sheath tumors: a single-arm phase 2 trial* (npj Precision Oncology 2025)
**Authors:** Anita Sveen (first), Ragnhild A Lothe (last/PI) — Oslo University Hospital

**Key correction — assay type:**
GEO SOFT shows  and . GPL35984 is the **Affymetrix Human Transcriptome Array 2.0 (HTA 2.0)**, not RNA-Seq. This is a microarray study.

**Annotation corrections:**
-  → corrected to ,  (ForeName LastName; previous had LastName First format)
-  → corrected from  to  (canonical portal value)
-  → reformatted 
-  → reformatted 
-  → removed from all 19 File entities

**File-level annotations set:**
- :  (Affymetrix microarray, NOT RNA-Seq)
- : 
- : 
- : 
- : 
- :  (Affymetrix CEL files expected)

**Files updated:** 19
