### ISSUE TITLE
add value: Massively Parallel Reporter Assay (MPRA)

### ISSUE THREAD

**Issue by anngvu** [nf-osi/nf-metadata-dictionary#132]
**Please describe why this concept is necessary**
See https://github.com/nf-osi/nf-metadata-dictionary/issues/109

**Please describe the situations in which this concept may apply**
SPORE consortium

**Comment by allaway** [comment]
## NADIA Curation Report

**Synapse Project:** [syn74315478](https://www.synapse.org/#!Synapse:syn74315478)

### Annotations Applied
| Field | Value |
|-------|-------|
| studyName | SARC031: A Phase 2 Trial of Selumetinib and Sirolimus for Adults with NF1-Related MPNST |
| diseaseFocus | Neurofibromatosis type 1 |
| manifestation | Malignant Peripheral Nerve Sheath Tumor |
| dataType | geneExpression, clinicalData |
| assay | rnaSeq |
| species | Homo sapiens |
| alternateDataRepository | insdc.sra:PRJNA1367141, insdc.sra:PRJNA1367142 |

### Curation Notes
- Phase 2 clinical trial RNA-seq data (selumetinib + sirolimus in NF1-MPNST adults)
- 2 FASTQ files in Raw Data folder
- No PMID found at time of curation; studyLeads = Not Available

**Status:** pendingReview ✓
