### ISSUE TITLE
Apply DRY principles to defining range (valid values)

### ISSUE THREAD

**Issue by anngvu** [nf-osi/nf-metadata-dictionary#135]
Related to https://github.com/Sage-Bionetworks/schematic/issues/329

["Don't repeat yourself" (DRY)](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself) is a principle of software development aimed at reducing repetition of software patterns, replacing it with abstractions or using data normalization to avoid redundancy.

For some time now, it has been recognized that defining a range for a property can be more DRY. Instead of a second step enumerating manually the valid values field, we can use the "parent" class that's already been defined. 

Put the parent class in valid values, and this should be expanded during build to pull in valid class values. For example, with the property `tumorType`, we should be able to put in `tumor` in the field valid values, and anything with `tumor` as a parent class should be enumerated in that field. This should be able to handle multiple classes, such as for defining the valid values range of `bodyPart` (which should probably be called `bodySite` to be more aligned with [CRDC-H](https://raw.githubusercontent.com/cancerDHC/ccdhmodel/main/model/schema/crdch_model.yaml) ) that takes "sample location referring to a named area of the body, inclusive of gross anatomical structures and organ part". Right now some classes have parent `organ`, and instead of changing the class term "heart" to have parent `body_part` (which would still be correct), should be able to use `bodySite` has range "organ, body_part". 

Benefits:
- If we have to change a term to do something like https://github.com/nf-osi/nf-metadata-dictionary/issues/123, we don't also have to do another update in the valid values field.
- Easier to handle very large sets of valid values.
- It's easier to see what a property _relates_ to; this abstraction actually makes it easier to think about.

**Comment by allaway** [comment]
## NADIA Curation Report

**Synapse Project:** [syn74315643](https://www.synapse.org/#!Synapse:syn74315643)

### Annotations Applied
| Field | Value |
|-------|-------|
| studyName | Loss-of-function of ubiquitin ligase adaptor LZTR1 triggers NF2-related schwannomatosis |
| diseaseFocus | Neurofibromatosis type 2, Schwannomatosis |
| manifestation | Schwannoma |
| dataType | proteomics |
| assay | label free mass spectrometry |
| species | Homo sapiens |
| tumorType | Schwannoma |
| diagnosis | Neurofibromatosis 2 |
| platform | Other |
| studyLeads | Francis Impens |
| institutions | VIB-UGent Center for Medical Biotechnology |
| alternateDataRepository | pride.project:PXD007035 |

### Curation Notes
- PRIDE proteomics dataset for LZTR1 schwannomatosis mechanism study
- 15 raw mass spec files in Raw Data folder
- dataType set to proteomics; assay = label free mass spectrometry

**Status:** pendingReview ✓
