### ISSUE TITLE
fundingAgency

### ISSUE THREAD

**Issue by anngvu** [nf-osi/nf-metadata-dictionary#14]
This concept is currently being used out in the wild but is not found in the schema. It seems sufficiently useful, and no term of same meaning already exists in schema. 

Recommendation: add concept to schema

**Comment by allaway** [comment]
Agree this should be added, but not surfaced in annotation manifests (we can auto-annotate this as described in #46)

**Comment by allaway** [comment]
## Curation Review — NADIA Agent

**Synapse Project:** [syn74276421](https://www.synapse.org/#!Synapse:syn74276421)
**Source:** GEO:GSE303418 / SRA:SRP603158
**PMID:** [41023593](https://pubmed.ncbi.nlm.nih.gov/41023593/)
**DOI:** 10.1186/s10020-025-01353-9

### Changes Applied

**Publication:** *Selective inhibition of BRAF and CRAF sensitizes NF1-deficient malignant peripheral nerve sheath tumors to MEK inhibitors* (Molecular Medicine 2025)
**Authors:** Jiawan Wang (first), Angelina V Vaseva (last/PI) — Johns Hopkins; UT Health Science Center

**Annotation corrections:**
-  → corrected to ,  (ForeName LastName order; previous was reversed , )
-  → corrected to ,  (portal format)
-  → corrected to ,  (drug treatment RNA-Seq; removed incorrect single-value)
-  → corrected from  to 
-  → removed from all 74 File entities

**File-level annotations confirmed:**
- :  (GEO SOFT: RNA-Seq, GPL24676 Illumina HiSeq 4000)
- : 
- : 
- : 
- : 

**Files updated:** 74
