### ISSUE TITLE
Convert boolean true/false values to yes/no in schema

### ISSUE THREAD

**Issue by allaway** [nf-osi/nf-metadata-dictionary#141]
**Describe the issue with the metadata**
As we discussed in stand-up today there are a couple of good reasons for converting boolean values to yes/no values
- user feedback from our community indicates yes/no is more relatable/digestible than booleans 
- our all-caps `BOOLEANS` are converted to python `Booleans` by schematic `associateMetadataWithFiles()` or by synapseclient - not sure which - but either way, this results in the Booleans not passing validation during re-annotation, and also doesn't comply with our schema. `yes`/`no` values should not have this coercion issue. 

Note: all of our boolean annotations will need to be updated on the portal as well!

**Comment by anngvu** [comment]
Update values in portal
- [ ] isCellLine
- [ ] isMultiSpecimen
- [ ] isMultiIndividual
- [ ] isPairedEnd
- [ ] isStranded

Update valid values in data model
- [ ] isCellLine
- [ ] isMultiSpecimen
- [ ] isMultiIndividual
- [ ] isPairedEnd
- [ ] isStranded

**Comment by allaway** [comment]
## NADIA Curation Report

**Synapse Project:** [syn74316090](https://www.synapse.org/#!Synapse:syn74316090)

### Annotations Applied
| Field | Value |
|-------|-------|
| studyName | Effect of depletion of NCOR2 on gene expression in neurofibroma cells |
| diseaseFocus | Neurofibromatosis type 1 |
| manifestation | Malignant Peripheral Nerve Sheath Tumor |
| dataType | geneExpression |
| assay | rnaSeq |
| species | Homo sapiens |
| tumorType | Malignant Peripheral Nerve Sheath Tumor |
| platform | Illumina |
| studyLeads | Yuehua Li |
| alternateDataRepository | geo:GSE201668, insdc.sra:PRJNA832582 |

### Curation Notes
- RNA-seq of NCOR2-depleted neurofibroma/MPNST cell lines
- 13 FASTQ files in Raw Data folder

**Status:** pendingReview ✓
