### ISSUE TITLE
Import NF-relevant cell lines from other sources

### ISSUE THREAD

**Issue by nfosi-service** [nf-osi/nf-metadata-dictionary#147]
**List the new value**
TBD -- need to look at cell lines table.

**Additional comments**
Presuming that everything in Cellosaurus should be in the Research Tools DB?

**Update: refined this issue and the only source for consideration is NF Tools DB**
- https://github.com/nf-osi/nf-metadata-dictionary/issues/229

**Comment by allaway** [comment]
In theory, yes, everything in Cellosaurus that is NF relevant should go into the Research Tools DB. However, the prototype was only NF1 (no NF2 or SWN), and we didn't have the time to import everything even for NF1; adding these will be a major focus of the next phase of that project! But we intend to get everything from cellosaurus that is NF1 relevant added for sure, and then can do NF2/SWN as time permits (or as new data comes in that need these added).

**Comment by allaway** [comment]
## NADIA Curation Report

**Synapse Project:** [syn74316193](https://www.synapse.org/#!Synapse:syn74316193)

### Annotations Applied
| Field | Value |
|-------|-------|
| studyName | Somatic CRISPR tumorigenesis and multiomic analysis reveal a pentose phosphate pathway dependency in NF1-associated MPNST |
| diseaseFocus | Neurofibromatosis type 1 |
| manifestation | Malignant Peripheral Nerve Sheath Tumor |
| dataType | geneExpression |
| assay | spatialTranscriptomics |
| species | Mus musculus |
| tumorType | Malignant Peripheral Nerve Sheath Tumor |
| platform | 10x Visium |
| studyLeads | Gavin R McGivney, Rebecca D Dodd |
| institutions | University of Iowa |
| fundingAgency | NCI NIH HHS, NINDS NIH HHS |
| pmid | 40802750 |
| doi | 10.1126/sciadv.adu2906 |
| alternateDataRepository | geo:GSE275277, insdc.sra:PRJNA1150162 |

### Curation Notes
- GPL24247 = 10x Genomics Visium; assay corrected to spatialTranscriptomics
- 37 FASTQ files in Raw Data folder
- studyLeads corrected from LastName-First to FirstName-Last
- Science Advances 2025 paper on somatic CRISPR NF1-MPNST model with pentose phosphate pathway

**Status:** pendingReview ✓
