### ISSUE TITLE
Automate doc builds

### ISSUE THREAD

**Issue by anngvu** [nf-osi/nf-metadata-dictionary#154]
Currently, the documentation can be a little out of sync (does not include new terms), because updates don't generate docs automatically; one needs to remember to pull updates in main do doc-gen locally as another PR. It probably makes sense to add a workflow so that merges to main will update docs as part of the workflow, since other steps have gradually been implemented in the GitHub infra.

**Comment by allaway** [comment]
## NADIA Curation Report

**Synapse Project:** [syn74316425](https://www.synapse.org/#!Synapse:syn74316425)

### Annotations Applied
| Field | Value |
|-------|-------|
| studyName | Somatic mosaic SOX10 indel mutations underlie a form of segmental schwannomatosis |
| diseaseFocus | Schwannomatosis |
| manifestation | Schwannoma |
| dataType | epigenomics |
| assay | methylationArray |
| species | Homo sapiens |
| tumorType | Schwannoma |
| diagnosis | Schwannomatosis |
| platform | Illumina |
| studyLeads | Merryl Terry, David A Solomon |
| institutions | University of California San Francisco |
| fundingAgency | NCI NIH HHS |
| pmid | 37821623 |
| doi | 10.1007/s00401-023-02641-6 |
| alternateDataRepository | geo:GSE239715, insdc.sra:PRJNA1000612 |

### Curation Notes
- EPIC 850k methylation array of schwannomas with mosaic SOX10 mutations
- 2 IDAT files in Raw Data folder
- dataType = epigenomics; assay = methylationArray; studyLeads corrected to FirstName-Last

**Status:** pendingReview ✓
