### ISSUE TITLE
Formalize template for processed RNA-seq data

### ISSUE THREAD

**Issue by anngvu** [nf-osi/nf-metadata-dictionary#159]
See also https://data.humantumoratlas.org/standard/rnaseq. 

We currently only have a metadata template for uploaded "raw data" (Level 1 data), but as more semi-processed and processed data are produced (Level 2+), it would be good to conceptualize a template for these  so that we document what attributes are expected to be carried over to processed data files, as well as which processed data-specific attributes should be present (e.g. workflow versions, quality scores). See ref above for differences in Level 1 vs Level 3 templates.

Note: Unlike raw data templates, processed data templates should be filled in programmatically through the workflow (ideally) or scripts. 

Relevant NF-OSI issues: [NFINT-688](https://sagebionetworks.jira.com/browse/NFINT-688)

**Comment by allaway** [comment]
@anngvu - I *think* this can be marked as complete. What do you think?

**Comment by allaway** [comment]
## NADIA Curation Report

**Synapse Project:** [syn74316991](https://www.synapse.org/#!Synapse:syn74316991)

### Annotations Applied
| Field | Value |
|-------|-------|
| studyName | Analysis of ENG-modulated gene expression profiles in malignant peripheral nerve sheath tumors |
| diseaseFocus | Neurofibromatosis type 1 |
| manifestation | Malignant Peripheral Nerve Sheath Tumor |
| dataType | geneExpression |
| assay | rnaSeq |
| species | Homo sapiens |
| tumorType | Malignant Peripheral Nerve Sheath Tumor |
| platform | Illumina |
| studyLeads | Osvaldo Graña |
| institutions | Spanish National Cancer Research Centre CNIO |
| alternateDataRepository | geo:GSE216792, insdc.sra:PRJNA895406 |

### Curation Notes
- RNA-seq of ENG (endoglin)-modulated MPNST cells; CNIO (Madrid)
- 5 FASTQ files in Raw Data folder
- No PMID found at time of curation; companion to GSE219148 (anti-endoglin antibody xenograft dataset)

**Status:** pendingReview ✓
