### ISSUE TITLE
compoundDose

### ISSUE THREAD

**Issue by anngvu** [nf-osi/nf-metadata-dictionary#16]
This concept is currently being used out in the wild but is not found in the schema. It seems sufficiently useful, and no term of same meaning already exists in schema. 

Recommendation: add concept to schema

**Comment by anngvu** [comment]
Already added

**Comment by allaway** [comment]
## Curation Review — NADIA Agent

**Synapse Project:** [syn74277555](https://www.synapse.org/#!Synapse:syn74277555)
**Source:** GEO:GSE317922
**PMID:** [41582719](https://pubmed.ncbi.nlm.nih.gov/41582719/)
**DOI:** 10.1242/dmm.052509

### Changes Applied

**Publication:** *Inhibition of Cxcr4 chemokine receptor signaling improves habituation learning in a zebrafish model of Neurofibromatosis* (Disease Models & Mechanisms 2025)
**Authors:** Andrew H Miller (first), Mary C Halloran (last/PI) — University of Wisconsin-Madison

**Key correction — manifestation:**
The original value  is **not a valid portal value**. The correct canonical value is .

**Annotation corrections:**
-  → corrected from  to  (valid portal manifestation)
-  → corrected to ,  (removed periods in names)
-  → removed from all 27 File entities

**File-level annotations confirmed:**
- :  (GEO SOFT: RNA-Seq, GPL18413 = Illumina HiSeq 2500 Danio rerio)
- :  (zebrafish model confirmed by GEO taxon and GPL18413)
- :  (behavioral/cognitive study, no tumor)
- : 
- :  (HiSeq 2500)

**Files updated:** 27
