### ISSUE TITLE
Remove extraneous items from imaging schema

### ISSUE THREAD

**Issue by allaway** [nf-osi/nf-metadata-dictionary#169]
e.g. genomics terms are showing up in imaging schema probably due to dependencies:

isStranded | libraryPrep | nucleicAcidSource | readLength | readPairOrientation | readStrandOrigin | runType

**Comment by anngvu** [comment]
Closing old issue that hasn't been an issue since 2022...

**Comment by allaway** [comment]
## NADIA Curation Report

**Synapse Project:** [syn74318066](https://www.synapse.org/#!Synapse:syn74318066)

### Annotations Applied
| Field | Value |
|-------|-------|
| studyName | Identifying transcriptomic pathways mediating radiotherapy response in malignant peripheral nerve sheath tumors |
| diseaseFocus | Neurofibromatosis type 1 |
| manifestation | Malignant Peripheral Nerve Sheath Tumor |
| dataType | geneExpression |
| assay | rnaSeq |
| species | Homo sapiens |
| tumorType | Malignant Peripheral Nerve Sheath Tumor |
| platform | Illumina |
| studyLeads | Iowis Zhu, Harish N Vasudevan |
| institutions | University of California San Francisco |
| fundingAgency | NCI NIH HHS |
| pmid | 41766654 |
| doi | 10.1172/JCI195652 |
| alternateDataRepository | geo:GSE290674 |

### Curation Notes
- RNA-seq of MPNST cell lines and xenografts after radiotherapy; JCI 2025
- 1 FASTQ file in Raw Data folder
- Part 3 of 3 companion datasets from JCI 2025 paper (PMID:41766654)

**Status:** pendingReview ✓
