### ISSUE TITLE
Find new term for report

### ISSUE THREAD

**Issue by allaway** [nf-osi/nf-metadata-dictionary#171]
Jaishri finds "report" as a catch all term for powerpoints, pdfs, certificate of analysis, etc, confusing because it's confused with a milestone report. We can: be more granular with the resourceType, or come up with a different catch-all term. Maybe it would be good to be slightly more granular.

**Comment by anngvu** [comment]
Going to close this as we currently have `result` and split last comment into separate enhancement issue.

**Comment by allaway** [comment]
## Curation Review — NADIA Agent

**Synapse Project:** [syn74318280](https://www.synapse.org/#!Synapse:syn74318280)
**Source:** GEO:GSE277653 / SRA:PRJNA1163293
**PMID:** [40168468](https://pubmed.ncbi.nlm.nih.gov/40168468/)
**DOI:** 10.2106/JBJS.24.01007

### Changes Applied

**Study title corrected** to match publication: *Molecular Evidence Supporting MEK Inhibitor Therapy in NF1 Pseudarthrosis* (JBJS 2025)

**Annotation corrections:**
- `studyName` → corrected to full publication title
- `manifestation` → changed from `Neurofibroma` to `Plexiform Neurofibroma` (pseudarthrosis is associated with plexiform neurofibromas at the fracture site in NF1)
- `dataType` → corrected to `geneExpression` (RNA-Seq by GEO SOFT; previous values included `genomicVariants`, `drugScreen`, `clinicalData` which were incorrect)
- `doi` → added `10.2106/JBJS.24.01007`
- `institutions` → updated to `Scottish Rite for Children, Dallas, Texas`; `University of Texas Southwestern Medical Center`
- `studyLeads` → corrected to `Nandina Paria`, `Jonathan J Rios` (first and last author, PubMed AuthorList)
- `fundingAgency` → corrected to `Department of Defense`, `NCI NIH HHS`, `Texas Neurofibromatosis Foundation` (from PubMed GrantList)
- `resourceStatus` → removed from all 91 File entities (Files must not carry this annotation)

**File-level annotations set:**
- `assay`: `rnaSeq` (GEO SOFT: `!Sample_library_strategy = RNA-Seq`)
- `species`: `Homo sapiens` (GEO taxon confirmed)
- `tumorType`: `Not Applicable` (primary cells from pseudarthrosis tissue, not tumor)
- `diagnosis`: `Neurofibromatosis 1`
- `platform`: `Illumina` (GPL34284)
- `fileFormat`: `fastq`
- `dataSubtype`: `raw`

**Files updated:** 91
