### ISSUE TITLE
Move docs to `/docs` branch and reconfigure Pages source

### ISSUE THREAD

**Issue by anngvu** [nf-osi/nf-metadata-dictionary#174]
Currently, our docs hosted on Pages are being built from `main`. However, there's a better [configuration option](https://docs.github.com/en/pages/getting-started-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site) to use a `/docs` dedicated branch so that Pages build is not run unnecessarily with each commit. Related: https://github.com/nf-osi/nf-metadata-dictionary/issues/154

**Comment by allaway** [comment]
## NADIA Curation Report

**Synapse Project:** [syn74318443](https://www.synapse.org/#!Synapse:syn74318443)

### Annotations Applied
| Field | Value |
|-------|-------|
| studyName | Identification of CD74-positive antigen presenting glioma cells in NF1 low-grade glioma |
| diseaseFocus | Neurofibromatosis type 1 |
| manifestation | Low-Grade Glioma NOS |
| dataType | geneExpression |
| assay | spatialTranscriptomics |
| species | Mus musculus |
| tumorType | Low-Grade Glioma |
| diagnosis | Neurofibromatosis 1 |
| platform | 10x Visium |
| studyLeads | Thomas De Raedt |
| alternateDataRepository | geo:GSE317486, insdc.sra:PRJNA1413414 |

### Curation Notes
- GPL24247 = 10x Genomics Visium spatial transcriptomics; 10 spatial samples
- 2 FASTQ files in Raw Data folder
- assay = spatialTranscriptomics; manifestation = Low-Grade Glioma NOS
- No PMID found at time of curation

**Status:** pendingReview ✓
