### ISSUE TITLE
Remove '_' in extended templates for compatibility with recent versions of schematic

### ISSUE THREAD

**Issue by anngvu** [nf-osi/nf-metadata-dictionary#175]
Tried today to generate `GenomicsAssayTemplate_Extended` with relatively recent version of schematic and failed; the standard `GenomicsAssayTemplate` works fine. If the '_' is removed the extended template can be generated. It is easier to just change the template label to ensure compatibility with most recent/future versions. 

Note: Extended templates are _not_ in the user-facing config https://github.com/nf-osi/NF_data_curator/blob/develop/www/config.json

**Comment by allaway** [comment]
resolved in  #179

**Comment by allaway** [comment]
## NADIA Curation Report

**Synapse Project:** [syn74318452](https://www.synapse.org/#!Synapse:syn74318452)

### Annotations Applied
| Field | Value |
|-------|-------|
| studyName | Combined CDK inhibition overcomes MEK inhibitor resistance in NF1-mutant plexiform neurofibromas |
| diseaseFocus | Neurofibromatosis type 1 |
| manifestation | Plexiform Neurofibroma |
| dataType | geneExpression, drugScreen |
| assay | rnaSeq |
| species | Homo sapiens |
| tumorType | Plexiform Neurofibroma |
| platform | Illumina |
| studyLeads | Zhichao Wang |
| alternateDataRepository | geo:GSE173577, insdc.sra:PRJNA726198 |

### Curation Notes
- RNA-seq of MEK inhibitor resistance in NF1-pNF cells; CDK inhibitor combination
- 25 FASTQ files in Raw Data folder
- No PMID found at time of curation

**Status:** pendingReview ✓
