### ISSUE TITLE
More consistent platform values to match GEO if possible

### ISSUE THREAD

**Issue by anngvu** [nf-osi/nf-metadata-dictionary#176]
Also fulfills this issue dug up from the internal annals -- [NFINT-86](https://sagebionetworks.jira.com/browse/NFINT-86?atlOrigin=eyJpIjoiYTBhOGE3ZWU4NDQ3NGFkNGI3YzNkODdjMTQ5MmU4OGIiLCJwIjoiaiJ9):

> For all values under the attribute/key <platform>, align spacing and ensure all values start with the instrumentation company name – e.g., Illumina Next Seq 550 (not Next Seq 550). Do this for both all files, and in the NF schema.

Mainly came up again as something that might help eliminate an additional mapping step for GEO vals.

**Comment by allaway** [comment]
resolved in  #179

**Comment by allaway** [comment]
## Curation Review — NADIA Agent

**Synapse Project:** [syn74318490](https://www.synapse.org/#!Synapse:syn74318490)
**Source:** GEO:GSE262030 / SRA:PRJNA1090069
**PMID:** [38585724](https://pubmed.ncbi.nlm.nih.gov/38585724/) (preprint); also published as PMID:41036607
**DOI:** 10.1101/2024.03.25.585959

### Changes Applied

**Publication:** *Pharmacogenomic synthetic lethal screens reveal hidden vulnerabilities and new therapeutic approaches for treatment of NF1-associated tumors* (bioRxiv 2024 / published 2024)

**Annotation corrections:**
- `studyName` → corrected: added 's' to 'tumors' (publication uses plural)
- `dataType` → corrected to `geneExpression`, `drugScreen` (RNA-Seq + drug screen; removed `clinicalData`, removed `genomicVariants`)
- `manifestation` → kept `Malignant Peripheral Nerve Sheath Tumor`, `Plexiform Neurofibroma` (correct)
- `doi` → added preprint DOI `10.1101/2024.03.25.585959`
- `studyLeads` → corrected to `Kyle B Williams`, `David A Largaespada` (ForeName LastName order)
- `institutions` → `University of Minnesota Masonic Cancer Center`
- `resourceStatus` → removed from all 103 File entities

**File-level annotations set:**
- `assay`: `rnaSeq` (GEO SOFT: `!Sample_library_strategy = RNA-Seq`)
- `species`: `Homo sapiens` (human MPNST/pNF cell lines)
- `tumorType`: `Malignant Peripheral Nerve Sheath Tumor`
- `diagnosis`: `Neurofibromatosis 1`
- `platform`: `Illumina` (GPL24676)
- `fileFormat`: `fastq`

**Files updated:** 103
