### ISSUE TITLE
Add [CUT&RUN] to [assay]

### ISSUE THREAD

**Issue by anngvu** [nf-osi/nf-metadata-dictionary#177]
**List the new value**
Value: `CUT&RUN`

**Provide definition and source for the new value**
Temp reference: 
Cleavage Under Targets & Release Using Nuclease (CUT&RUN) is a new technology that utilizes target-specific primary antibodies and pAG-MNase to isolate protein-DNA complexes on native chromatin for analysis by qPCR or next-gen sequencing (NGS) [[cellsignal](https://www.cellsignal.com/applications/cut-and-run)]

**Comment by allaway** [comment]
resolved in  #179

**Comment by allaway** [comment]
## Curation Review — NADIA Agent

**Synapse Project:** [syn74318610](https://www.synapse.org/#!Synapse:syn74318610)
**Source:** GEO:GSE273881 / SRA:PRJNA1143539
**PMID:** [40864686](https://pubmed.ncbi.nlm.nih.gov/40864686/)
**DOI:** 10.1126/scitranslmed.adq5492

### Changes Applied

**Publication:** *NF1-depleted ER+ breast cancers are differentially sensitive to CDK4/6 inhibitors* (Science Translational Medicine 2025)

**Annotation corrections:**
- `dataType` → corrected to `epigenomics` (GEO SOFT shows `!Series_type = Genome binding/occupancy profiling by high throughput sequencing`, `!Sample_library_strategy = ChIP-Seq`; the previous values `genomicVariants`, `proteomics`, `clinicalData` were all incorrect)
- `studyLeads` → corrected to `Ze-Yi Zheng`, `Eric C Chang` (ForeName LastName order)
- `doi` → added `10.1126/scitranslmed.adq5492`
- `institutions` → corrected to `Baylor College of Medicine Lester and Sue Smith Breast Center`
- `resourceStatus` → removed from all 33 File entities

**File-level annotations set:**
- `assay`: `ChIPSeq` (confirmed by GEO SOFT ChIP-Seq library strategy)
- `species`: `Homo sapiens` (breast cancer cell lines)
- `tumorType`: `Breast Invasive Carcinoma` (NF1-depleted ER+ breast cancer cell lines)
- `diagnosis`: `Neurofibromatosis 1` (NF1 loss-of-function context)
- `platform`: `Illumina` (GPL18573 NextSeq 500)
- `fileFormat`: `fastq`

**Files updated:** 33
