### ISSUE TITLE
Add [M3 MPNST] to [modelSystemName]

### ISSUE THREAD

**Issue by anngvu** [nf-osi/nf-metadata-dictionary#178]
**List the new value**
Value: `M3 MPNST`

**Provide definition and source for the new value**
This is a cell line. Need to ask whether there's a more accurate name/reference.

**Comment by allaway** [comment]
resolved in  #179

**Comment by allaway** [comment]
## NADIA Curation Report

**Synapse Project:** [syn74318656](https://www.synapse.org/#!Synapse:syn74318656)

### Annotations Applied
| Field | Value |
|-------|-------|
| studyName | Characterization of non-NF2 related schwannomatosis at single cell resolution |
| diseaseFocus | Schwannomatosis |
| manifestation | Schwannoma |
| dataType | geneExpression |
| assay | single-cell RNA-seq |
| species | Mus musculus |
| tumorType | Schwannoma |
| diagnosis | Schwannomatosis |
| platform | Illumina |
| studyLeads | Sonu Subudhi |
| alternateDataRepository | geo:GSE282045 |

### Curation Notes
- scRNA-seq of non-NF2 schwannomatosis mouse model tumors
- 1 FASTQ file in Raw Data folder
- assay = single-cell RNA-seq
- No PMID found at time of curation

**Status:** pendingReview ✓
