### ISSUE TITLE
Add Cherry Imaging platforms

### ISSUE THREAD

**Issue by anngvu** [nf-osi/nf-metadata-dictionary#186]
**List the new value**
Value: 
- `Cherry Imaging FACE Platform`
- `Cherry Imaging TRACE Platform`

**Provide definition and source for the new value**
Definition:
 - TRACE: Full skin 3D imaging platform designed for research; uses a handheld scanner to capture thousands of images from multiple angles, which can be analyzed to create precise skin morphology model with a 100 micron accuracy to assess treatment results over time.
 - FACE: 3D imaging platform for in-office data collection that includes scanning station to creates accurate 3D skin morphology and color models.
Source url: https://www.cherryimaging.com/

**Are there similar but not-quite-right values?**
Please list if applicable.

**Additional comments**

**Comment by allaway** [comment]
## Curation Review — NADIA Agent

**Synapse Project:** [syn74319019](https://www.synapse.org/#!Synapse:syn74319019)
**Source:** SRA:PRJNA1222828
**PMID:** Not found (unpublished dataset)

### Changes Applied

**SRA metadata confirmed:** RNA-Seq treatment experiment. SRA ExpXml: `GSM8790229: MS03 - 0.1 micromolar BSJ-04-0146 - 24 hours`, Mus musculus, Illumina HiSeq 4000. BSJ-04-0146 is a selective FAK1 (PTK2) inhibitor, confirming the drug treatment context.

**Annotation corrections:**
- `manifestation` → kept `Schwannoma` (NF2 null schwannoma cell line model)
- `dataType` → corrected to `geneExpression`, `drugScreen` (removed `clinicalData`)
- `studyLeads` → kept `Not Available` (no PMID or publication found)
- `diseaseFocus` → kept `Neurofibromatosis type 2`, `Schwannomatosis` (correct)
- `resourceStatus` → removed from all 48 File entities

**File-level annotations set:**
- `assay`: `rnaSeq` (RNA-Seq confirmed by SRA)
- `species`: `Mus musculus` (confirmed)
- `tumorType`: `Schwannoma`
- `diagnosis`: `Neurofibromatosis 2`
- `platform`: `Illumina` (HiSeq 4000)

**Files updated:** 48
