### ISSUE TITLE
Accidentally pulled-in `cell lysate` column for Proteomics template

### ISSUE THREAD

**Issue by anngvu** [nf-osi/nf-metadata-dictionary#189]
**Describe the issue with the metadata**
This appears to affect only Proteomics templates (see generated template [here](https://docs.google.com/spreadsheets/d/1uckyOZigljo6SiaoXffHDRkdYdE8a5TbjNuwi_waP5g/edit#gid=0)) where `cell lysate` is somehow pulled in as column likely because of a stray `REQUIRED` somewhere. Reference definition: https://github.com/nf-osi/nf-metadata-dictionary/blob/main/modules/Template/Template.csv#L17

**Comment by allaway** [comment]
## Curation Review — NADIA Agent

**Synapse Project:** [syn74319150](https://www.synapse.org/#!Synapse:syn74319150)
**Source:** SRA:PRJNA1100739
**PMID:** Not found (no PMID in NCBI SRA elink)

### Changes Applied

**SRA/BioProject metadata confirmed:** RNA-Seq study of uveal melanoma in GNAQ/Nf1 double-mutant mice. BioProject title: "Melanoma and peripheral nerve sheath tumors in GNAQ and Nf1 mutant mice". NextSeq 2000, Mus musculus. The study examines co-occurrence of GNAQ mutation + Nf1 loss.

**Annotation corrections:**
- `manifestation` → changed from `Neurofibroma` to `Malignant Peripheral Nerve Sheath Tumor` (study explicitly about MPNSTs in Nf1 mutant mice)
- `dataType` → kept `geneExpression` (RNA-Seq correct)
- `studyLeads` → kept `Not Available` (no publication linked)
- `institutions` → added `NC State University Center for Human Health and the Environment` (from SRA submitter info)
- `resourceStatus` → removed from all 42 File entities

**File-level annotations set:**
- `assay`: `rnaSeq`
- `species`: `Mus musculus` (confirmed by SRA scientific name)
- `tumorType`: `Malignant Peripheral Nerve Sheath Tumor`
- `diagnosis`: `Neurofibromatosis 1`
- `platform`: `Illumina` (NextSeq 2000)

**Files updated:** 42
