### ISSUE TITLE
Add tests for template generation

### ISSUE THREAD

**Issue by anngvu** [nf-osi/nf-metadata-dictionary#190]
See https://github.com/nf-osi/nf-metadata-dictionary/issues/173 for parent/master testing issue.

We want to generate templates each time a data model is updated to make sure they can be generated and that they look right. This could help prevent issues such as https://github.com/nf-osi/nf-metadata-dictionary/issues/189

**Comment by allaway** [comment]
## Curation Review — NADIA Agent

**Synapse Project:** [syn74319200](https://www.synapse.org/#!Synapse:syn74319200)
**Source:** GEO:GSE179582 / SRA:PRJNA744235
**PMID:** [35789380](https://pubmed.ncbi.nlm.nih.gov/35789380/)
**DOI:** 10.1158/2159-8290.CD-21-1671

### Changes Applied

**Publication:** *PRC2-Inactivating Mutations in Cancer Enhance Cytotoxic Response to DNMT1-Targeted Therapy via Enhanced Innate Immune Sensing* (Cancer Discovery 2022)

**Note:** Three companion datasets exist for this paper: syn74319200 (ChIP-Seq, GSE179582), syn74319609 (ChIP-Seq H3K36me3, PRJNA836551), syn74319650 (ATAC-seq, PRJNA744564), and syn74319813 (RNA-seq, PRJNA744233). All have been curated and linked to PMID:35789380.

**Annotation corrections:**
- `dataType` → corrected to `epigenomics` only (GEO SOFT: `!Sample_library_strategy = ChIP-Seq`; removed `genomicVariants`, `drugScreen`, `clinicalData`)
- `doi` → added `10.1158/2159-8290.CD-21-1671`
- `studyLeads` → corrected to `Amish J Patel`, `Ping Chi` (ForeName LastName order)
- `institutions` → `Memorial Sloan Kettering Cancer Center`
- `resourceStatus` → removed from all 45 File entities

**File-level annotations set:**
- `assay`: `ChIPSeq` (GEO SOFT confirmed)
- `species`: `Homo sapiens`
- `tumorType`: `Malignant Peripheral Nerve Sheath Tumor`
- `diagnosis`: `Neurofibromatosis 1`
- `platform`: `Illumina` (GPL16791 HiSeq 2500)

**Files updated:** 45
