### ISSUE TITLE
Add `workflow report` to resourceType

### ISSUE THREAD

**Issue by anngvu** [nf-osi/nf-metadata-dictionary#193]
**List the new value**

Definition: "Workflow-generated reports of analysis of primary data (e.g. sequence or structural)"
Derived subclass from http://edamontology.org/data_2048

This is needed to annotate  `_*report`  files from nextflow processing and used to be more specific/helpful than "report". See also https://github.com/nf-osi/nf-metadata-dictionary/issues/171

**Comment by allaway** [comment]
## NADIA Curation Report

**Synapse Project:** [syn74319511](https://www.synapse.org/#!Synapse:syn74319511)

### Annotations Applied
| Field | Value |
|-------|-------|
| studyName | Gene expression of Vestibular Schwannoma tumors versus tumor-adjacent cochlear nerve tissue |
| diseaseFocus | Neurofibromatosis type 2, Schwannomatosis |
| manifestation | Vestibular Schwannoma |
| dataType | geneExpression |
| assay | rnaSeq |
| species | Homo sapiens |
| tumorType | Vestibular Schwannoma |
| diagnosis | Neurofibromatosis 2 |
| platform | Illumina |
| alternateDataRepository | insdc.sra:PRJNA1150102 |

### Curation Notes
- RNA-seq comparing VS tumors to adjacent cochlear nerve tissue
- 40 FASTQ files in Raw Data folder
- No PMID found; studyLeads = Not Available

**Status:** pendingReview ✓
