### ISSUE TITLE
Minimal template for workflow meta/report files

### ISSUE THREAD

**Issue by anngvu** [nf-osi/nf-metadata-dictionary#195]
See https://github.com/nf-osi/nf-metadata-dictionary/issues/130. A large number of workflow output files are reports or workflow meta (containing the commands, versions, and params used). These need their own templates and don't require the `dataType` and `dataSubtype` properties.

The template should have these properties:
- `resourceType`
- `assay`
- `fileFormat`
- `workflow` 
- `workflowLink`

Notes:
- Also add `linkedDataset` so that it's clear which dataset(s) a workflow report/meta file describes. 
- https://www.encodeproject.org/profiles/ link entities to a "step_run" in the workflow so entities can be organized temporally at when they were produced in the wf. This would require parsing the nextflow DAG.

**Comment by allaway** [comment]
## NADIA Curation Report

**Synapse Project:** [syn74319563](https://www.synapse.org/#!Synapse:syn74319563)

### Annotations Applied
| Field | Value |
|-------|-------|
| studyName | Imaging Mass Cytometry Data from Static and Growing Vestibular Schwannomas |
| diseaseFocus | Neurofibromatosis type 2, Schwannomatosis |
| manifestation | Vestibular Schwannoma |
| dataType | image, proteomics |
| assay | other |
| species | Homo sapiens |
| tumorType | Vestibular Schwannoma |
| studyLeads | Gregory Grace, Michael Haley |
| doi | 10.48420/26510758.v1 |
| alternateDataRepository | doi:10.48420/26510758.v1 |

### Curation Notes
- Imaging mass cytometry (IMC) dataset from VS tumor biobank
- 5 files in Raw Data folder
- dataType = image, proteomics; assay = other (IMC is protein-based imaging)

**Status:** pendingReview ✓
