### ISSUE TITLE
Add numeric type validation to `age` to hopefully make data more consistent

### ISSUE THREAD

**Issue by anngvu** [nf-osi/nf-metadata-dictionary#196]
Related to 

- https://github.com/nf-osi/nf-metadata-dictionary/issues/118 
- #173 (Step 3: Get annotations from the test entities and check what they actually look like)

Context: Linked to bug where `age` has been uploaded inconsistently as numeric or character, leading to two columns of the same name in Synapse. (https://sagebionetworks.jira.com/browse/NFINT-719?focusedCommentId=151153). 

![image](https://user-images.githubusercontent.com/32753274/183784288-3b287f57-793f-48d5-9177-e4a4cc071cf6.png)

One can also see this in the [screenshot ](https://github.com/Sage-Bionetworks/schematic/issues/821#issue-1306578399) of duplicated columns (e.g. `DiagnosisMONDO` as both string and double) that @lopierra has reported from her INCLUDE testing. 

After this, we would need to go back and coerce any character `age` values.

**Comment by allaway** [comment]
## NADIA Curation Report

**Synapse Project:** [syn74319573](https://www.synapse.org/#!Synapse:syn74319573)

### Annotations Applied
| Field | Value |
|-------|-------|
| studyName | Perfusion-weighted imaging in vestibular schwannoma: the influence of post-contrast delay on imaging biomarkers |
| diseaseFocus | Neurofibromatosis type 2, Schwannomatosis |
| manifestation | Vestibular Schwannoma |
| dataType | image, clinicalData |
| assay | other |
| species | Homo sapiens |
| tumorType | Vestibular Schwannoma |
| studyLeads | Felipe Constanzo, Bernardo Corrêa de Almeida Teixeira |
| doi | 10.6084/m9.figshare.22785472.v1 |
| alternateDataRepository | doi:10.6084/m9.figshare.22785472.v1 |

### Curation Notes
- MRI perfusion-weighted imaging dataset for VS; Figshare repository
- 9 files in Raw Data folder
- dataType = image, clinicalData

**Status:** pendingReview ✓
