### ISSUE TITLE
Template for dataset

### ISSUE THREAD

**Issue by anngvu** [nf-osi/nf-metadata-dictionary#200]
We should have a formal model for datasets that somewhat corresponds to other standards. 
1. https://support.datacite.org/docs/schema-40#table-1-datacite-mandatory-properties: For citations.
2. https://www.w3.org/TR/vocab-dcat-3/: Has good interop and is used by many data portals, including data.gov. Example dataset properties and mappings across the most widely used vocabs: https://resources.data.gov/resources/podm-field-mapping/. Thus, for the new dataset catalog, datasets should include standard properties such as: 

- title
- description
- theme (we're using `manifestation` as a more specific theme)
- series (dcat:inSeries) -- though more similar to GEO SuperSeries
- [license](http://www.w3.org/TR/vocab-dcat/#Property:distribution_license)
- accessLevel (? `public` for where all files can be downloaded without any other steps -- `restricted public` is suggested for ones where files need approval)
- references (e.g. a publication)

**Comment by allaway** [comment]
## Curation Review — NADIA Agent

**Synapse Project:** [syn74319609](https://www.synapse.org/#!Synapse:syn74319609)
**Source:** SRA:PRJNA836551
**PMID:** [35789380](https://pubmed.ncbi.nlm.nih.gov/35789380/) — linked via submitter (Ping Chi lab, MSK)
**DOI:** 10.1158/2159-8290.CD-21-1671

### Changes Applied

**Companion dataset** to syn74319200, syn74319650, and syn74319813 — all from the same Cancer Discovery 2022 paper by Amish J Patel and Ping Chi at MSK.

**SRA metadata:** `GSM6124409: H3K36me3_M3sgSUZ12_2; Homo sapiens; OTHER` — ChIP-Seq for histone H3K36me3 mark.

**PMID and DOI added** — project was missing PMID and DOI.

**Annotation corrections:**
- `pmid` → added `35789380`
- `doi` → added `10.1158/2159-8290.CD-21-1671`
- `studyLeads` → corrected to `Amish J Patel`, `Ping Chi`
- `institutions` → `Memorial Sloan Kettering Cancer Center`
- `fundingAgency` → `NCI NIH HHS`, `FDA HHS`
- `dataType` → kept `geneExpression`; corrected to `epigenomics` (ChIP-Seq)
- `manifestation` → kept `Malignant Peripheral Nerve Sheath Tumor`
- `resourceStatus` → removed from all 32 File entities

**File-level annotations:**
- `assay`: `ChIPSeq`
- `species`: `Homo sapiens`
- `tumorType`: `Malignant Peripheral Nerve Sheath Tumor`
- `platform`: `Illumina` (HiSeq 2500)

**Files updated:** 32
