### ISSUE TITLE
Make `species` and (maybe) `tissue` required annotation properties

### ISSUE THREAD

**Issue by anngvu** [nf-osi/nf-metadata-dictionary#202]
@allaway Any comments for making the templates somewhat stricter?

**Comment by allaway** [comment]
I think it would be fine to require both. species for sure - i would posit that most of our data has a "species." Tissue is a bit harder, I think that could be confusing for some data where tissue. As long as Not Applicable is an available option, it's probably fine to enforce both. Are you looking for feedback on other things that should be required?

**Comment by allaway** [comment]
## NADIA Curation Report

**Synapse Project:** [syn74319680](https://www.synapse.org/#!Synapse:syn74319680)

### Annotations Applied
| Field | Value |
|-------|-------|
| studyName | NF2 is Essential for Human Endoderm Development |
| diseaseFocus | Neurofibromatosis type 2 |
| manifestation | Schwannoma |
| dataType | geneExpression |
| assay | rnaSeq |
| species | Homo sapiens |
| tumorType | Not Applicable |
| platform | Illumina |
| alternateDataRepository | insdc.sra:PRJNA1141571 |

### Curation Notes
- RNA-seq of NF2-knockout hiPSC-derived endoderm cells
- 15 FASTQ files in Raw Data folder
- tumorType = Not Applicable (developmental biology study, not tumor)
- No PMID found; studyLeads = Not Available

**Status:** pendingReview ✓
