### ISSUE TITLE
Add "AnnotatedSomaticVariants", "AnnotatedGermlineVariants" to dataType

### ISSUE THREAD

**Issue by anngvu** [nf-osi/nf-metadata-dictionary#203]
**List the new value**
This is primarily for MAF files generated from the VEP+vcf2maf [workflow](https://sagebionetworks.jira.com/wiki/spaces/WF/pages/2696937476/Variant+annotation+workflow+for+SNVs+and+indels), to reflect that GDC makes a distinction between e.g. _simple_ somatic mutation, _"which have not been annotated or filtered, called from aligned reads"_ vs _annotated_ somatic mutations, which can be linked to some annotation workflow.

**Provide definition and source for the new value**
Definition: Data (typically MAF or VCF files) that contain annotated somatic mutations calls.
Source url: [annotated somatic mutations](https://docs.gdc.cancer.gov/Data_Dictionary/viewer/#?view=table-definition-view&id=annotated_somatic_mutation)

Corresponding defs for germline.

**Comment by allaway** [comment]
## NADIA Curation Report

**Synapse Project:** [syn74319702](https://www.synapse.org/#!Synapse:syn74319702)

### Annotations Applied
| Field | Value |
|-------|-------|
| diseaseFocus | Neurofibromatosis type 2 |
| manifestation | Vestibular Schwannoma |
| dataType | clinicalData |
| assay | other |
| species | Homo sapiens |
| tumorType | Vestibular Schwannoma |
| doi | 10.3389/fphar.2022.941854 |

### Curation Notes
- Supplementary data file from Qu-Du-San-Jie study (Frontiers Pharmacology 2022) on VS treatment outcomes
- 1 supplementary file in Raw Data folder
- diseaseFocus corrected: Neurofibroma removed, set to Neurofibromatosis type 2 / VS

**Status:** pendingReview ✓
