### ISSUE TITLE
Add NRG (mice) to modelSystemName

### ISSUE THREAD

**Issue by anngvu** [nf-osi/nf-metadata-dictionary#205]
**List the new value**
NRG

**Provide definition and source for the new value**
Definition: Extremely immunodeficient mice with a targeted knockout mutation in recombination activating gene 1 (Rag1) and a complete null allele of the IL2 receptor common gamma chain.
Source url: https://www.jax.org/strain/007799

**Additional comments**
Context: JIRA ticket NFOSI-308

**Comment by allaway** [comment]
## NADIA Curation Report

**Synapse Project:** [syn74319714](https://www.synapse.org/#!Synapse:syn74319714)

### Annotations Applied
| Field | Value |
|-------|-------|
| diseaseFocus | Neurofibromatosis type 2 |
| manifestation | Vestibular Schwannoma |
| dataType | clinicalData |
| assay | other |
| species | Homo sapiens |
| tumorType | Vestibular Schwannoma |
| doi | 10.3389/fphar.2022.941854 |

### Curation Notes
- Supplementary data file from Qu-Du-San-Jie study (Frontiers Pharmacology 2022) on VS treatment outcomes
- 1 supplementary file in Raw Data folder
- diseaseFocus corrected: Neurofibroma removed, set to Neurofibromatosis type 2 / VS

**Status:** pendingReview ✓
