### ISSUE TITLE
Update schematic check CI to not use poetry install, use PyPi releases

### ISSUE THREAD

**Issue by anngvu** [nf-osi/nf-metadata-dictionary#207]
It seems as if testing with schematic (v22.8.1) depends on some extra poetry dependencies as seen in logs [here](https://github.com/nf-osi/nf-metadata-dictionary/actions/runs/3192123479/jobs/5209267080). This short circuits testing with other versions as well.

**Comment by allaway** [comment]
## NADIA Curation Report

**Synapse Project:** [syn74319728](https://www.synapse.org/#!Synapse:syn74319728)

### Annotations Applied
| Field | Value |
|-------|-------|
| diseaseFocus | Neurofibromatosis type 2 |
| manifestation | Vestibular Schwannoma |
| dataType | clinicalData |
| assay | other |
| species | Homo sapiens |
| tumorType | Vestibular Schwannoma |
| doi | 10.3389/fphar.2022.941854 |

### Curation Notes
- Supplementary data file from Qu-Du-San-Jie study (Frontiers Pharmacology 2022) on VS treatment outcomes
- 1 supplementary file in Raw Data folder
- diseaseFocus corrected: Neurofibroma removed, set to Neurofibromatosis type 2 / VS

**Status:** pendingReview ✓
