### ISSUE TITLE
Add "Generic Measures" template

### ISSUE THREAD

**Issue by anngvu** [nf-osi/nf-metadata-dictionary#208]
Not sure if this is the best template name/conception, but it would be good to have something like the Clinical Assay Template, which is currently used for a lot of `.csv` data with summary measures at different time points from patients, but this would be for technically non-clinical, non-human data.

**Comment by allaway** [comment]
## NADIA Curation Report

**Synapse Project:** [syn74319734](https://www.synapse.org/#!Synapse:syn74319734)

### Annotations Applied
| Field | Value |
|-------|-------|
| studyName | Atypical neurofibromas reveal distinct epigenetic features with proximity to benign and malignant NF1-associated tumors |
| diseaseFocus | Neurofibromatosis type 1 |
| manifestation | Malignant Peripheral Nerve Sheath Tumor, Plexiform Neurofibroma, Schwannoma |
| dataType | epigenomics |
| assay | methylationArray |
| species | Homo sapiens |
| tumorType | Neurofibroma |
| diagnosis | Neurofibromatosis 1 |
| platform | Illumina |
| studyLeads | Catena Kresbach, Ulrich Schüller |
| institutions | University Medical Center Hamburg-Eppendorf |
| pmid | 36866403 |
| doi | 10.1093/neuonc/noad053 |
| alternateDataRepository | geo:GSE216262, insdc.sra:PRJNA892883 |

### Curation Notes
- EPIC 850k methylation array of atypical neurofibromas; Neuro-Oncology 2023
- 2 IDAT files in Raw Data folder
- studyLeads corrected from LastName-First to FirstName-Last

**Status:** pendingReview ✓
