### ISSUE TITLE
Add NWB to fileFormat

### ISSUE THREAD

**Issue by anngvu** [nf-osi/nf-metadata-dictionary#209]
Noticed that we don't actually have this as an option for fileFormat

**List the new value**
Value: `NWB` (neurodata without borders)

**Provide definition and source for the new value**
https://www.nwb.org/

**Additional comments**
For context, see this [PR](https://github.com/nf-osi/dcc-site/pull/261/files#diff-a753d54ea64daf609f94d11bc00a5604c284822cbfb3740131df7bd61a4dbee0)

**Comment by anngvu** [comment]
@cconrad8 Just a heads up that I added you a secondary assignee as I'm curating issues that would be good for our interactive practicum next week. Don't worry about it too much.

**Comment by allaway** [comment]
## Curation Review — NADIA Agent

**Synapse Project:** [syn74319743](https://www.synapse.org/#!Synapse:syn74319743)
**Source:** GEO:GSE198220 / SRA:PRJNA814235
**PMID:** Not in GEO pubmedids field (no PMID linked)

### Changes Applied

**SRA/GEO metadata confirmed:** RNA-Seq of zebrafish (Danio rerio) MPNST tumor microenvironment. GEO title confirmed: "Profiling the cancer-prone microenvironment in a zebrafish model for MPNST". NextSeq 500, Danio rerio.

**Annotation corrections:**
- `manifestation` → kept `Malignant Peripheral Nerve Sheath Tumor` (correct)
- `dataType` → kept `geneExpression` (correct)
- `studyLeads` → corrected to `Dereje Jima` (SRA submitter from CHHE, NC State)
- `institutions` → `NC State University Center for Human Health and the Environment`
- `resourceStatus` → removed from all 35 File entities

**File-level annotations:**
- `assay`: `rnaSeq`
- `species`: `Danio rerio` (zebrafish, confirmed by GEO taxon and SRA scientific name)
- `tumorType`: `Malignant Peripheral Nerve Sheath Tumor`
- `diagnosis`: `Neurofibromatosis 1`
- `platform`: `Illumina` (NextSeq 500)

**Files updated:** 35
