### ISSUE TITLE
Template for chemical and biomolecular characterization data (DLS)

### ISSUE THREAD

**Issue by anngvu** [nf-osi/nf-metadata-dictionary#213]
Currently, the templates are geared towards assays of biological samples. However, there is some interest in submitting characterization data of engineered materials (e.g. polymeric nanoparticles or PNPs). Assays for materials characterization might include NMR spectroscopy, Dynamic Light Scattering, etc. 

Currently, it is unclear what attributes are important when submitting data from Dynamic Light Scattering (DLS). For example, if RNA-seq assay template suggests including information like `libraryPrep`, what is the equivalent for DLS? And what would a generic materials characterization template look like?

**Comment by allaway** [comment]
This is an interesting problem. Here's a paper I found about CHADA, "a
novel approach for the definition of terminology, classification and
metadata for materials characterization methods":
https://www.sciencedirect.com/science/article/pii/S235249281930087X

Not sure what CHADA stands for.

**Comment by anngvu** [comment]
I think CHADA=CHaracterization DAta

Anyway, after looking through a couple of other databases/sites, I think we can use something that is pretty close to the minimal ISA-TAB-Nano specification.

There is an example for DLS data, which is nice: https://wiki.nci.nih.gov/display/icr/isa-tab-nano#ISATABNano-ISA-TAB-NanoExampleFiles

**Comment by allaway** [comment]
## Curation Review — NADIA Agent

**Synapse Project:** [syn74319958](https://www.synapse.org/#!Synapse:syn74319958)
**Source:** PLoS Medicine supplementary file: DOI:10.1371/journal.pmed.1003734.s010
**PMID:** Not directly linked (paper PMID:34370721 — "Improved Diagnostic Accuracy by Use of the Nuclear Ki-67 Antigen")

### Changes Applied

**Study type note:** This project represents a supplementary Excel/data file from a PLoS Medicine paper about diagnostic tests distinguishing MPNST from plexiform neurofibroma. The deposited data is likely a supplementary dataset table.

**Annotation corrections:**
- `studyName` → corrected from file-path-derived name to descriptive title
- `manifestation` → corrected to `Malignant Peripheral Nerve Sheath Tumor`, `Plexiform Neurofibroma` (appropriate for MPNST vs PN diagnostic study)
- `dataType` → corrected to `clinicalData` (clinical/imaging diagnostic data, not geneExpression)
- `doi` → corrected to paper DOI `10.1371/journal.pmed.1003734`
- `studyLeads` → `Jeffrey J Szymanski`, `R Taylor Sundby` (as named in project)
- `resourceStatus` → removed from 1 File entity

**Files updated:** 1
