### ISSUE TITLE
Reconsider curatedData value

### ISSUE THREAD

**Issue by anngvu** [nf-osi/nf-metadata-dictionary#214]
Split from https://github.com/nf-osi/nf-metadata-dictionary/issues/171

> Consider removing curatedData as value, or determine better, more precise term.

**Comment by anngvu** [comment]
Was removed

**Comment by allaway** [comment]
## NADIA Curation Report

**Synapse Project:** [syn74319964](https://www.synapse.org/#!Synapse:syn74319964)

### Annotations Applied
| Field | Value |
|-------|-------|
| studyName | Volumetric results of patients analyzed by two readers for volumetric plexiform neurofibroma assessment |
| diseaseFocus | Neurofibromatosis type 1 |
| manifestation | Plexiform Neurofibroma, Cutaneous Neurofibroma |
| dataType | clinicalData |
| assay | other |
| species | Homo sapiens |
| tumorType | Plexiform Neurofibroma |
| studyLeads | Lennart Well, Kimberly Döbel |
| doi | 10.1371/journal.pgen.1009517 |
| alternateDataRepository | doi:10.1371/journal.pgen.1009517.s005 |

### Curation Notes
- PLoS Genetics supplementary volumetric data file for NF1 pNF imaging study
- 1 XLSX file in Raw Data folder

**Status:** pendingReview ✓
