### ISSUE TITLE
add key: [isFilteredReads]

### ISSUE THREAD

**Issue by jaybee84** [nf-osi/nf-metadata-dictionary#215]
**List the new key**
Using [OLS](https://www.ebi.ac.uk/ols/index) or a similar resource, please find a standard term that fits your needs. OLS-listed NCIT and OBI dictionaries are preferred sources. Non-OLS sources of ground truth for specific items such as ONCOTREE for cancer types, or GEO for platform definitions are also appropriate. 
Key:`isFilteredReads`

**Provide definition and source for the new key**
Definition: This key defines whether the reads in the processed file has been filtered by adding a "PASS" filter or other filters as determined by the data generator
Source url: 
Related key: https://www.ebi.ac.uk/ols/ontologies/genepio/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FGENEPIO_0000087

**Please describe why this concept is necessary**
This key will only need to be added to processed genomic data files. This helps users select and download only filtered data if needed and reduces sifting through unfiltered data files.

**Please describe the situations in which this concept may apply**
I as a researcher am trying to download only files that have filtered reads for my analysis. The folder contains both filtered and unfiltered files. I would like to select the filtered files using a metadata facet.

**Comment by allaway** [comment]
## NADIA Curation Report

**Synapse Project:** [syn74319972](https://www.synapse.org/#!Synapse:syn74319972)

### Annotations Applied
| Field | Value |
|-------|-------|
| studyName | Malignant Peripheral Nerve Sheath Tumors are Comprised of Two Epigenetic Subtypes |
| diseaseFocus | Neurofibromatosis type 1 |
| manifestation | Malignant Peripheral Nerve Sheath Tumor |
| dataType | geneExpression, epigenomics |
| assay | rnaSeq |
| species | Homo sapiens |
| tumorType | Malignant Peripheral Nerve Sheath Tumor |
| platform | Illumina |
| studyLeads | Jeff Liu |
| alternateDataRepository | geo:GSE207400, geo:GSE207399 |

### Curation Notes
- RNA-seq + methylation of MPNST epigenetic subtypes; GEO GSE207399/207400
- 2 files in Raw Data folder
- No PMID found; studyLeads = Jeff Liu (GEO submitter)

**Status:** pendingReview ✓
