### ISSUE TITLE
Update `schematic-ci` workflow because GitHub Actions now uses Ubuntu 22.04 by default

### ISSUE THREAD

**Issue by anngvu** [nf-osi/nf-metadata-dictionary#217]
Between the last PR Actions run (https://github.com/nf-osi/nf-metadata-dictionary/actions/runs/3323932909/jobs/5494887090) and this latest run (https://github.com/nf-osi/nf-metadata-dictionary/actions/runs/3586306030/jobs/6035343752), the GH's default runner switched from Ubuntu 20.04 to Ubuntu 22.04, so some system dependencies specified in the workflow failed to install:

> Hit:1 http://azure.archive.ubuntu.com/ubuntu jammy InRelease
> Get:2 http://azure.archive.ubuntu.com/ubuntu jammy-updates InRelease [114 kB]
> Get:3 http://azure.archive.ubuntu.com/ubuntu jammy-backports InRelease [99.8 kB]
> Get:4 http://azure.archive.ubuntu.com/ubuntu jammy-security InRelease [110 kB]
> Get:5 https://packages.microsoft.com/ubuntu/22.04/prod jammy InRelease [10.5 kB]
> ...
> E: Unable to locate package python3.8-venv
> E: Couldn't find any package by glob 'python3.8-venv'
> E: Couldn't find any package by regex 'python3.8-venv'
> Error: Process completed with exit code 100.

**Comment by allaway** [comment]
## NADIA Curation Report

**Synapse Project:** [syn74320003](https://www.synapse.org/#!Synapse:syn74320003)

### Annotations Applied
| Field | Value |
|-------|-------|
| studyName | Epigenome analysis of schwannomas across genetic backgrounds |
| diseaseFocus | Schwannomatosis, Neurofibromatosis type 2 |
| manifestation | Schwannoma |
| dataType | epigenomics, genomicVariants |
| assay | methylationArray |
| species | Homo sapiens |
| tumorType | Schwannoma |
| diagnosis | Schwannomatosis |
| platform | Illumina |
| studyLeads | Erik A Williams, David A Solomon |
| institutions | University of California San Francisco |
| fundingAgency | NCI NIH HHS |
| pmid | 37436963 |
| doi | 10.1093/neuonc/noad121 |
| alternateDataRepository | insdc.sra:PRJNA808968 |

### Curation Notes
- EPIC methylation array of schwannomas from NF2, LZTR1, SMARCB1, and sporadic backgrounds
- 1 IDAT file in Raw Data folder
- PMID identified via BioProject elink

**Status:** pendingReview ✓
