### ISSUE TITLE
Add [3D electron microscopy] to [Assay]

### ISSUE THREAD

**Issue by jaybee84** [nf-osi/nf-metadata-dictionary#225]
**List the new value**
Value: `3D electron microscopy`

Using [OLS](https://www.ebi.ac.uk/ols/index) or a similar resource, please find a standard term that fits your needs. OLS-listed NCIT and OBI dictionaries are preferred sources. Non-OLS sources of ground truth for specific items such as ONCOTREE for cancer types, or GEO for platform definitions are also appropriate. 

**Provide definition and source for the new value**

**Are there similar but not-quite-right values?**
Definition: Any form of microscopy in which the interactions of electrons with the specimens are used to provide information about the final structure of that specimen
Source url: https://www.ebi.ac.uk/ols/ontologies/ncit/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FNCIT_C16854

**Additional comments**

**Comment by allaway** [comment]
## Curation Review — NADIA Agent

**Synapse Project:** [syn74320121](https://www.synapse.org/#!Synapse:syn74320121)
**Source:** SRA:PRJNA781907
**PMID:** [39100928](https://pubmed.ncbi.nlm.nih.gov/39100928/) — discovered via SRA→PubMed elink
**DOI:** 10.1016/j.isci.2024.110294

### Changes Applied

**Publication:** *NF1-dependent disruption of the blood-nerve-barrier is improved by blockade of P2RY14* (iScience 2024)
**Authors:** Jennifer Patritti-Cram (first), Nancy Ratner (last/PI) — Cincinnati Children's Hospital Medical Center

**PMID and DOI added** — project was missing both.

**Annotation corrections:**
- `pmid` → added `39100928`
- `doi` → added `10.1016/j.isci.2024.110294`
- `studyLeads` → corrected to `Jennifer Patritti-Cram`, `Nancy Ratner`
- `institutions` → `Cincinnati Childrens Hospital Medical Center`
- `fundingAgency` → `NINDS NIH HHS`
- `manifestation` → changed from `Neurofibroma` to `Plexiform Neurofibroma` (NF1 peripheral nerve lesions affecting blood-nerve barrier — plexiform NF context)
- `resourceStatus` → removed from all 8 File entities

**File-level annotations:**
- `assay`: `rnaSeq`
- `species`: `Mus musculus` (confirmed by SRA `NF1`)
- `tumorType`: `Not Applicable` (peripheral nerve, not tumor)
- `diagnosis`: `Neurofibromatosis 1`
- `platform`: `Illumina` (HiSeq 2500)

**Files updated:** 8
