### ISSUE TITLE
Add [3D Confocal Imaging] to [Assay]

### ISSUE THREAD

**Issue by jaybee84** [nf-osi/nf-metadata-dictionary#226]
**List the new value**
Value: `3D Confocal Imaging`

Using [OLS](https://www.ebi.ac.uk/ols/index) or a similar resource, please find a standard term that fits your needs. OLS-listed NCIT and OBI dictionaries are preferred sources. Non-OLS sources of ground truth for specific items such as ONCOTREE for cancer types, or GEO for platform definitions are also appropriate. 

**Provide definition and source for the new value**

**Are there similar but not-quite-right values?**
Definition: A system of (usually) epifluorescence light microscopy in which a fine laser beam of light is scanned over the object through the objective lens. The technique is particularly good at rejecting light from outside the plane of focus and so produces higher effective resolution than is normally achieved.
Source url:https://www.ebi.ac.uk/ols/ontologies/ncit/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FNCIT_C17753

**Additional comments**

**Comment by allaway** [comment]
## Curation Review — NADIA Agent

**Synapse Project:** [syn74320156](https://www.synapse.org/#!Synapse:syn74320156)
**Source:** GEO:GSE207512 / GSE207513 / GSE207514 / SRA:PRJNA855955 / PRJNA855954 / PRJNA855956
**PMID:** [37044095](https://pubmed.ncbi.nlm.nih.gov/37044095/)
**DOI:** 10.1016/j.xcrm.2023.101002

### Changes Applied

**Publication:** *N-acetylcysteine overcomes NF1 loss-driven resistance to PI3Kα inhibition in breast cancer* (Cell Reports Medicine 2023)
**Authors:** Priska Auf der Maur (first), Mohamed Bentires-Alj (last/PI) — University of Basel / FMI

**Annotation corrections:**
- `studyName` → corrected to full publication title (removed dataset-specific suffix `(RNAseq_WAP)`)
- `doi` → added `10.1016/j.xcrm.2023.101002`
- `studyLeads` → corrected to `Priska Auf der Maur`, `Mohamed Bentires-Alj`
- `institutions` → `University of Basel`, `Friedrich Miescher Institute for Biomedical Research`
- `fundingAgency` → `Not Applicable (External Study)` (no NIH grants; Swiss funding)
- `dataType` → corrected to `geneExpression`, `proteomics`, `drugScreen`
- `manifestation` → kept `Neurofibroma` (NF1 loss in breast cancer; no classic NF1 tumor)
- `resourceStatus` → removed from all 281 File entities

**Note:** Three GEO series span this project: GSE207512 (mouse RNA-seq), GSE207513 (likely human RNA-seq), GSE207514 (proteomics/other). The file-level annotations were set based on GSE207512 (mouse RNA-Seq by GEO SOFT). Data manager should verify species/assay for files from GSE207513 and GSE207514.

**Files updated:** 281
