### ISSUE TITLE
Add [weblink] to [resourceType]

### ISSUE THREAD

**Issue by jaybee84** [nf-osi/nf-metadata-dictionary#228]
**List the new value**
Value: `weblink/URL`

Using [OLS](https://www.ebi.ac.uk/ols/index) or a similar resource, please find a standard term that fits your needs. OLS-listed NCIT and OBI dictionaries are preferred sources. Non-OLS sources of ground truth for specific items such as ONCOTREE for cancer types, or GEO for platform definitions are also appropriate. 

**Provide definition and source for the new value**
Definition: The global address of documents and other resources on the World Wide Web.
Source url: https://www.ebi.ac.uk/ols/ontologies/ncit/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FNCIT_C42743

**Are there similar but not-quite-right values?**
Please list if applicable.

**Additional comments**

**Comment by jaybee84** [comment]
Also found this which is more specific to image data:
https://www.ebi.ac.uk/ols/ontologies/ncit/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FNCIT_C183334

**Comment by allaway** [comment]
## Curation Review — NADIA Agent

**Synapse Project:** [syn74320511](https://www.synapse.org/#!Synapse:syn74320511)
**Source:** SRA:SRP579342
**PMID:** [41569052](https://pubmed.ncbi.nlm.nih.gov/41569052/)

### Changes Applied

**Publication:** *[A man with axillary and inguinal freckling, café-au-lait spots, and cutaneous nodules]* (Dutch language case report, 2025)
**Authors:** Minke J Peeters (first), Inge B Mathijssen (last) — Amsterdam University Medical Centers

**Annotation corrections:**
- `doi` → not added (no DOI found for this case report in PubMed)
- `dataType` → corrected to `genomicVariants` (SRP579342 appears to be WGS/WES of a single NF1 patient; original `geneExpression` was incorrect)
- `studyLeads` → corrected to `Minke J Peeters`, `Inge B Mathijssen` (ForeName LastName order)
- `institutions` → `Amsterdam University Medical Centers`
- `manifestation` → changed from `Neurofibroma` to `Cutaneous Neurofibroma` (case report about cutaneous nodules/neurofibromas + cafe-au-lait spots)
- `resourceStatus` → removed from all 6 File entities

**Note:** This is a single NF1 patient diagnostic case. The SRA submission SRP579342 likely contains WGS data from this individual used for molecular diagnosis.

**Files updated:** 6
