### ISSUE TITLE
Import/sync cell lines from NF Tools Database 

### ISSUE THREAD

**Issue by anngvu** [nf-osi/nf-metadata-dictionary#229]
This issue is for [cell line resources](https://www.synapse.org/#!Synapse:syn26438037/tables/query/eyJzcWwiOiJTRUxFQ1QgKiBGUk9NIHN5bjI2NDM4MDM3IiwgInNlbGVjdGVkRmFjZXRzIjpbeyJjb25jcmV0ZVR5cGUiOiJvcmcuc2FnZWJpb25ldHdvcmtzLnJlcG8ubW9kZWwudGFibGUuRmFjZXRDb2x1bW5WYWx1ZXNSZXF1ZXN0IiwgImNvbHVtbk5hbWUiOiJyZXNvdXJjZVR5cGUiLCAiZmFjZXRWYWx1ZXMiOlsiQ2VsbCBMaW5lIl19XSwgImluY2x1ZGVFbnRpdHlFdGFnIjp0cnVlLCAib2Zmc2V0IjowLCAibGltaXQiOjI1fQ==) only. Many (40-50%?) but not all are available. 

For frequent cross-database syncing, some script might be useful.  

Relevant to https://github.com/nf-osi/nf-metadata-dictionary/pull/224

**Comment by allaway** [comment]
Note, we should have more coming online within the next few months, as Rancho will be curating more data for this database for us :) So hopefully it will become more comprehensive soon!
