### ISSUE TITLE
Metadata tidying/presentation: reform camelcased assay values

### ISSUE THREAD

**Issue by allaway** [nf-osi/nf-metadata-dictionary#236]
This is low priority, but I think it would add a lot of polish to the portal to deprecate the camelcase attributes. See, for example, here: 

<img width="1322" alt="Screen Shot 2023-01-11 at 5 11 58 PM" src="https://user-images.githubusercontent.com/20408008/211952119-c211f1e7-d65c-42e8-912f-fb3e35e0f265.png">

The portal has logic to convert camelCased column names/annotation keys to Title Case, but this doesn't apply to annotation values.

**Comment by anngvu** [comment]
Updated scope to assays to be more concise. Just for context, this is of the same type of work as reformation of platform values in PR https://github.com/nf-osi/nf-metadata-dictionary/pull/179.
