### ISSUE TITLE
Update metadata dictionary docs

### ISSUE THREAD

**Issue by cconrad8** [nf-osi/nf-metadata-dictionary#276]
Hi @allaway @anngvu 
Can we update this? / could someone show me how?
https://nf-osi.github.io/nf-metadata-dictionary

It says "Last updated on 2022-12-09" so I assume that is accurate. 

Thanks!

**Comment by allaway** [comment]
Hey @anngvu , I think it wuold just be re-running this https://github.com/nf-osi/nf-metadata-dictionary/blob/main/docs/index.Rmd and updating the results here: https://github.com/nf-osi/nf-metadata-dictionary/blob/main/docs/index.html

However, what do you think about making this an Action so it just happens automatically on every new release?

**Comment by allaway** [comment]
(now I see there's actually an issue for that already: https://github.com/nf-osi/nf-metadata-dictionary/issues/154)
