### ISSUE TITLE
age

### ISSUE THREAD

**Issue by anngvu** [nf-osi/nf-metadata-dictionary#28]
This concept is currently being used out in the wild but is not found in the schema. It seems sufficiently useful, and no term of same meaning already exists in schema. Note: Need also ageUnit? 

Recommendation: add concept to schema

**Comment by allaway** [comment]
Agree that ageUnit would be helpful.

**Comment by allaway** [comment]
Oops, I see this is here already - relates to #101

**Comment by allaway** [comment]
FYI: I plan to add both `age` and `ageUnit` as annotations to the Synodos LGG data. I probably should have included this in the last PR, but forgot....

**Comment by anngvu** [comment]
Ah yeah, I can add this in a new PR.

**Comment by allaway** [comment]
Thanks!!

For ageUnit values: what is your opinion on plurality (e.g., day vs days, year vs years)?

**Comment by anngvu** [comment]
I think "day" is better, but maybe should be "days" for consistency with timePointUnit, which has valid values seconds, minutes, hours, days, etc.

**Comment by allaway** [comment]
Hmm, alright - sounds good! I'll go with days/years for now but we can revisit as needed down the road.
