### ISSUE TITLE
concreteType

### ISSUE THREAD

**Issue by anngvu** [nf-osi/nf-metadata-dictionary#32]
This concept is currently being used out in the wild, but there is no data associated with it, and it’s of uncertain necessity. 

Recommendation: terminate existence out in the wild

**Comment by anngvu** [comment]
This is actually a Synapse property (like `createdBy`). At the time of making the issue, I hadn't gotten to this [section](https://python-docs.synapse.org/build/html/Entity.html?highlight=property#properties-and-annotations-implementation-details). So yeah, don't remove `concreteType`. Instead, add `concreteType` to dictionary but note something like "This is not a user-added annotation but automatically set by the Synapse platform to describe the underlying storage model used for the resource". That way, an outsider looking at a fileview has some idea of what this column means and can know to ignore it.

**Comment by allaway** [comment]
I'd be curious to know if this has been added as an annotation by accident in any cases. It's possible to do this with `etag` at least - I've seen (due to Data Curator App bugs) etag exist both as an annotation (not the actual system etag) and as the system metadata. I wonder if there are instances of this happening with concreteType too?

**Comment by allaway** [comment]
I would also suggest that we don't surface this in Views as it's not useful to most NF end users.

**Comment by anngvu** [comment]
There's only small subset of fileviews that have `concreteType`, so maybe it was a bug. Example: [syn15666651](https://www.synapse.org/#!Synapse:syn15666651/tables/). I'll remove the column from these views, but still good to include the definition in the schema for reference as a non-user annotation property.

|fileview    |values_for_term |
|:-----------|:---------------|
|syn15666830 |                |
|syn15666651 |NA              |
|syn15666926 |                |
|syn17038350 |NA              |
|syn15666932 |                |
|syn15667121 |                |
|syn15666931 |                |
|syn7817226  |NA              |
|syn15666933 |NA              |
|syn15666930 |NA              |
|syn15666928 |                |
|syn15666677 |NA              |
|syn8449638  |NA              |
|syn15666927 |                |
|syn15666937 |                |
|syn15666923 |NA              |

**Comment by allaway** [comment]
Ah, got it. Thanks for clarifying! Agree it should go in the dictionary. :)

**Comment by anngvu** [comment]
@allaway Couldn't remove `concreteType` from [syn17038350](https://www.synapse.org/#!Synapse:syn17038350/tables/) because nf-osi is not admin.

**Comment by allaway** [comment]
the NF-OSI Sage team should have access to all the DHART-SPORE projects now. There were a few local sharing settings on folders within the project, so let me know if you still have trouble, I might have missed one.
