### ISSUE TITLE
Need ability to annotate RNAseq files with additional keys for crispr/drug tx

### ISSUE THREAD

**Issue by allaway** [nf-osi/nf-metadata-dictionary#320]
**Describe the issue with the metadata**
Currently the RNAseq manifest does not allow me to add genePerturbed, genePerturbationType, genePerturbationMethod, or experimentalCondition, which is helpful when annotating drug treated cells that also have crispr/sirna/shrna modifications. I think we removed these on purpose a while back, but now I miss them. I think we used to have them in the "extended" genomics assay manifest - maybe we should bring that back?

**Comment by aditya-nath-sage** [comment]
@allaway @anngvu is this in relation to RNASeqTemplate or ScRNASeqTemplate?

**Comment by allaway** [comment]
@aditya-nath-sage  - sorry that I missed this question. I was talking about RNA-seq, but it would make sense to add this to scRNAseq too. What do you think?

**Comment by aditya-nath-sage** [comment]
I could definitely add it to scRNAseq as well, I'll create another branch and do this.

**Comment by allaway** [comment]
Also needed to add these columns today in the epigenetics sequencing assay template. might be nice to incldue them there too!
