### ISSUE TITLE
fileType

### ISSUE THREAD

**Issue by anngvu** [nf-osi/nf-metadata-dictionary#34]
This concept is currently being used out in the wild when what should be used instead is the standard existing term fileFormat. 

Recommendation: replace instances of non-compliant term with fileFormat

**Comment by allaway** [comment]
Found related term FileType, same type of issue. Fixing it now. Will fix fileType -> fileFormat while I am at it.

**Comment by allaway** [comment]
This one has been resolved, removed both FileType and fileType annotations and moved the values for these annotations to fileFormat.
