### ISSUE TITLE
issue with Tissue

### ISSUE THREAD

**Issue by allaway** [nf-osi/nf-metadata-dictionary#344]
**Describe the issue with the metadata**
Tissue is a useful annotation term typically for describing the source of RNA/DNA/protein for an experiment. However, this annotation breaks down in certain scenarios. For example, if the specimen is saliva, or a whole organism (e.g c. elegans) then we can no longer use this annotation term, and there's no other term to capture this type of information. 

**List alternative**
I'm not sure exactly what to do - open for discussion. A couple of thoughts:

a) look to HTAN, GDC, or other to see how they capture this information and add that as a new term (upside: more specific, downside: higher annotation burden) 
b) same as above, but instead of adding a new term, replace "tissue" with this newer, more general term (upside: no change in annotation burden, downside: less specific, need to remap terms) 

**Additional comments**

**Comment by allaway** [comment]
Oo I like that because it still maintains our hierarchy

**Comment by allaway** [comment]
Should we just adopt the NCIT types of biospecimens wholesale? This would keep us consistent with CDISC, GDC, etc... https://www.ebi.ac.uk/ols4/ontologies/ncit/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FNCIT_C70713?lang=en

**Comment by allaway** [comment]
Though, there are a lot of terms there and there's a lot of semantic overlap (e.g. at some point all of the samples in this project from Stanford were saliva samples and at other points they were DNA...). Especially if people are annotating tumor samples I can imagine it could start to get a little headache inducing to have that many options (e.g. you could have a specimen that is Tumor Tissue and a Solid Tissue Specimen and a Xenograft and a Post Neoadjuvant Therapy Sample and a ....

**Comment by allaway** [comment]
The enums for biospecimen_type in GDC look pretty good and comprehensive while not being overly granular: 

https://docs.gdc.cancer.gov/Data_Dictionary/viewer/#?view=table-definition-view&id=molecular_test&anchor=biospecimen_type

**Comment by allaway** [comment]
Ok, and in looking thru those terms, I recognize a lot of those as things we already call "tissue". Even though a lot of them are not actually tissues, e.g. Buffy Coat. 
 https://www.synapse.org/#!Synapse:syn16858331/tables/query/eyJzcWwiOiJTRUxFQ1QgdGlzc3VlLCBjb3VudCgqKSBGUk9NIHN5bjE2ODU4MzMxIGdyb3VwIGJ5IHRpc3N1ZSAiLCAiaW5jbHVkZUVudGl0eUV0YWciOnRydWUsICJvZmZzZXQiOjAsICJsaW1pdCI6MjV9

We do use some of these terms already as Tissue. Now I'm a little bit of a loss at what to do - keep it the same (and just add the new terms), or rip off the band-aid and select all of the "biospecimen types" currently under tissue that match the GDC terms, and put them under a new term in our dictionary for biospeciment type.

**Comment by cconrad8** [comment]
I think changing tissue to biospecimen type makes the most sense.  And biospecimen type will include all tissues as well as saliva and the rest of them.

**Comment by anngvu** [comment]
I think that's going back to option 2) actually, in the way I originally thought of this. We would have to migrate tissue to key-value data to biospecimenType.

**Comment by cconrad8** [comment]
Yeah sampleType to me makes sense!

**Comment by jaybee84** [comment]
Adding my 2c:
Given that `tissue` has caused a lot of confusion among the external collaborators, I support the adoption of BiospecimenType or SpecimenType. Voting for this one, since we already use `specimenID`, `parentBiospecimenID` in our current templates.

**Comment by allaway** [comment]
Hi all:

That sounds great - on standup today we decided to go with changing tissue
to specimenType, and adding the GDC terms.
