### ISSUE TITLE
sampleIdentifier

### ISSUE THREAD

**Issue by anngvu** [nf-osi/nf-metadata-dictionary#35]
This concept is currently being used out in the wild but is not found in the schema. Its usage/meaning is confusing, and it’s unclear whether it should be added to the schema. Note: Why are values TRUE/FALSE? 

Recommendation: ?

**Comment by allaway** [comment]
I have no idea what's going on with this annotation. It probably means something to someone (e.g. custom investigator annotation), but it doesn't appear to provide any useful info for our portal.

**Comment by allaway** [comment]
My suggestion would be to leave this one as-is
