### ISSUE TITLE
Update registered JSON schemas such as superdataset, etc. more automatically

### ISSUE THREAD

**Issue by anngvu** [nf-osi/nf-metadata-dictionary#398]
Linked discussion [in Slack](https://sagebionetworks.slack.com/archives/C6KQHAGJX/p1707929919982509).

So this has two parts:
- First, when something like `modules/Assay` changes, the JSON schemas need to be rebuilt, similar to how NF.jsonld is rebuilt. NF.jsonld format "targets" the DCA application, while json format "targets" the Synapse platform.
- If changes are merged, JSON schema needs to be re-registered with Synapse registry.

**Comment by cconrad8** [comment]
@anngvu Can you explain why we have the 

`Validation Schema = superdataset`

 
 in synapse in addition to our data model? 

I’m getting confused on what that part does that our data model doesn’t?
