### ISSUE TITLE
Discuss adding grant start end dates/embargo end date to synapse Portal - Project View syn52677631

### ISSUE THREAD

**Issue by cconrad8** [nf-osi/nf-metadata-dictionary#459]
Problem: When reviewing the project closeout/annotations, I find that I am looking at both github projects and the synapse project to make sure they are in sync and check annotation status, project closeout etc. 

We have discussed this prior on synapse vs. github projects but some ideas worth having a discussion on:
- whether our project start/end dates should be visible to funders/PIs?
- integrating to automate with data flow app
- automated annotation check

**Comment by anngvu** [comment]
If we make this change, let's update the Portal - Study schema first.

**Comment by anngvu** [comment]
Additional discussion this week, and I think back to "this is hard to maintain because embargo end dates change and researchers don't always release data on time".
