### ISSUE TITLE
Create a Portal Publication model

### ISSUE THREAD

**Issue by anngvu** [nf-osi/nf-metadata-dictionary#478]
As with Portal Study and Portal Dataset model, though this is more similar to Portal Study, which existed before its formalization here, while Portal Dataset was completely new.

**Comment by anngvu** [comment]
New publication model should take into account issue #479

**Comment by aditya-nath-sage** [comment]
PR:[ ](https://github.com/nf-osi/nf-metadata-dictionary/pull/542)
