### ISSUE TITLE
Improve portal "publication" concept to differentiate between primary and secondary uses of studies

### ISSUE THREAD

**Issue by anngvu** [nf-osi/nf-metadata-dictionary#479]
From https://sagebionetworks.jira.com/browse/NFINT-805. Depends on #478.

> Recently, we have been asked a few times about what publications are the “primary” publication for a dataset and what publications represent secondary use of data. It would be great to differentiate these in the portal data and UI, kind of like on the NF Tools Database. 
> 
> However, there are a couple of questions that come to mind for me:
> 
> 1 - What is a secondary publication? if a PI re-uses their own data for the same study, should we call that primary or secondary? My vote would be secondary. 
> 
> 2 - Can a study have multiple primary publications (yes, probably, because it is not 1-1 datasets to studies, but happy to discuss this more.

**Comment by allaway** [comment]
Lol, I was about to vote for these questions, but then I realized I posted the initial issue 😅
