### ISSUE TITLE
Add `Private Access` to `accessType` for PortalDataset

### ISSUE THREAD

**Issue by anngvu** [nf-osi/nf-metadata-dictionary#482]
`accessType` will now be used, and this value will help make clear when a PortalDataset is still private.

**Comment by allaway** [comment]
Hey! This makes sense. I'm wondering if you or I should write a quick script to update this annotation. I have an older script kicking around somewhere, but it was slow and a bit of a pain to use as it involved tons of ACL queries and (IIRC) some manual curation for ARs. 

There's a REST service that should grab this information for us more easily. Not sure if it would be any faster: https://sagebionetworks.slack.com/archives/C0AFCTGEQ/p1721840221098519 but might be worth using. I believe we talked about this with Jay earlier, and that the main issue with using this service "live" in the portal is that we couldn't precalculate facet information, so it couldn't easily be used as a facet. Maybe this is a reasonable workaround.
