### ISSUE TITLE
Add template for ChIP-seq assay

### ISSUE THREAD

**Issue by allaway** [nf-osi/nf-metadata-dictionary#532]
**Describe the issue with the metadata**
It would be helpful to have a chip-seq specific template. EpigeneticsSequencingAssay has content that is not relevant (e.g. bisulfiteConversionKitID) and is missing relevant content (e.g. assayTarget for the pulldown). 

**Additional comments**

**Comment by anngvu** [comment]
ChIP-seq specific template could also include antibody used. https://pmc.ncbi.nlm.nih.gov/articles/PMC3431496/#sec13

**Comment by changtotheintothemoon** [comment]
Hi Robert @allaway,

I found the section on Epigenetics sequencing assays here:
[https://github.com/nf-osi/nf-metadata-dictionary/blob/main/modules/Template/Data.yaml#L271-L299](https://github.com/nf-osi/nf-metadata-dictionary/blob/main/modules/Template/Data.yaml#L271-L299)

For ChIP-seq, here’s a list of possible types, though I'm not sure how many of these are relevant to NF projects. Please let me know if there are specific types we should focus on implementing:

- **Transcription Factor (TF) ChIP-seq**
- **Polymerase ChIP-seq** (e.g., RNA Pol II ChIP-seq)
- **Cohesin and CTCF ChIP-seq**
- **Mediator Complex ChIP-seq**
- **Histone Variant ChIP-seq** (e.g., H2A.Z, H3.3)
- **Acetylation-Specific or Phosphorylation-Specific ChIP-seq**
- **DNA-Binding Protein ChIP-seq** (e.g., p300/CBP ChIP-seq)
- **Chromatin Remodeler ChIP-seq**

Let me know your thoughts or any suggestions on implementing this. Thanks!
