### ISSUE TITLE
Add Prss56Cre/+ and Tom/+ to modelSystemName

### ISSUE THREAD

**Issue by cconrad8** [nf-osi/nf-metadata-dictionary#549]
**List the new value**
Value: "Prss56Cre/+, Tom/+, Nf1fl/fl" and "Prss56Cre/+, Tom/+" models 
Definition:
Source url:

**Comment by cconrad8** [comment]
Related project: https://www.synapse.org/Synapse:syn51356824/files/

**Comment by allaway** [comment]
Hey! If you haven't already, can you check the NFTC for these tools? If they don't exist, maybe @changtotheintothemoon could add them. If they do exist, just want to make sure the names match so that the data shows up on the tools central page for these mice.

**Comment by cconrad8** [comment]
Yup, I'll look into it!
