### ISSUE TITLE
Fix existing typo in class name

### ISSUE THREAD

**Issue by anngvu** [nf-osi/nf-metadata-dictionary#550]
Typo discovered in new template development for "EpigenomiscAssayTemplate" [sic]

**Comment by changtotheintothemoon** [comment]
Typo have been found and fixed in data.yaml
https://github.com/nf-osi/nf-metadata-dictionary/pull/543/commits/a793c575f3e9e33f6d4ee8af9362df7df208e90b

Typo have been fixed in https://github.com/nf-osi/nf-metadata-dictionary/issues/532 branch
