### ISSUE TITLE
modelSystemStrainNomenclature

### ISSUE THREAD

**Issue by anngvu** [nf-osi/nf-metadata-dictionary#62]
This concept is currently being used out in the wild when what should be used instead is the standard existing term modelSystemName. Note: modelSystemStrainNomenclature was previously removed from schema without being also removed from a template, which is why it may have have persisted.

Recommendation: remove from template dependencies and terminate existence out in the wild

**Comment by anngvu** [comment]
#### Resolved
- In syn25795489, it looks like values in modelSystemStrainNomenclature had been migrated to modelSystemName, but modelSystemStrainNomenclature was just not removed.
- In syn21669676, no annotations in modelSystemStrainNomenclature so could be safely removed
- In syn21993642, no annotations in modelSystemStrainNomenclature so could be safely removed

#### To do
- In syn18918530, annotation values in modelSystemStrainNomenclature need to be migrated to modelSystemName

**Comment by cconrad8** [comment]
@anngvu this looks like it was previously complete? I don't see modelSystemStrainNomenclature anymore
