### ISSUE TITLE
add key: Resource_id

### ISSUE THREAD

**Issue by allaway** [nf-osi/nf-metadata-dictionary#73]
**List the new key**
`Resource_id`

**Provide definition and source for the new key**
Definition: A UUID for a Resource from the NF Research Tools database. 
Source url: Sage Bionetworks

**Please describe why this concept is necessary**
This will not be used by external folks (at least, for now). This will be a UUID that allows us to link data files in the portal to resources curated in this database (https://lucid.app/lucidchart/3a118e5e-8884-48d1-af91-f03987bb0df8/edit?shared=true&page=pu72__N3nK2O#)

**Please describe the situations in which this concept may apply**
Linking cell lines, animal model data, to curated resource database.

**Comment by anngvu** [comment]
@allaway For consistency with the [Resource table](https://www.synapse.org/#!Synapse:syn26450069/tables/) and with all other ids, e.g. `studyId`, `projectId`, etc., I would add this as `resourceId`. I know it's `Resource_id` in the [Studies](https://www.synapse.org/#!Synapse:syn16787123/tables/) table, but we should change it to `resourceId` there.

**Comment by allaway** [comment]
Hey @anngvu, I suggested `Resource_id` because it's called that in the resource database data model (https://docs.google.com/spreadsheets/d/15fwIhZw7YfhPkzOfQhj6zU_5-_7ywS05-L8qOjMIVdM/edit#gid=0). The camelCase'd values in the Resource table will eventually be switched to display names (`schematic` is converting these to camelcase...to be resolved https://github.com/nf-osi/nf-metadata-dictionary/issues/73). 

Anyway, _eventually_ `Resource_id` will be consistent with the NF resources db. I am fine with changing it to `resourceId` to make it consistent with the portal naming conventions, though - either way works for me, as it will be inconsistent with either one or the other!

**Comment by allaway** [comment]
Oops, sorry, I linked to the wrong issue: I meant to link here https://github.com/Sage-Bionetworks/schematic/issues/543
