### ISSUE TITLE
Add [IDT xGen Exome Research Panel] to [libraryPreparationMethod]

### ISSUE THREAD

**Issue by jaybee84** [nf-osi/nf-metadata-dictionary#76]
**List the new value**
Value: `IDT xGen Exome Research Panel`

Using [OLS](https://www.ebi.ac.uk/ols/index) or a similar resource, please find a standard term that fits your needs. OLS-listed NCIT and OBI dictionaries are preferred sources. Non-OLS sources of ground truth for specific items such as ONCOTREE for cancer types, or GEO for platform definitions are also appropriate. 

**Provide definition and source for the new value**
Definition: xGen Exome Research Panel v2 targets only the coding sequences (CDS) of human coding genes in the RefSeq 109 database. xGen Exome Research Panel v2 consists of 5′ biotin–modified oligonucleotide probes that are individually synthesized and individually analyzed by ESI-MS and optical density (OD) measurement. xGen Exome Research Panel v2 consists of 415,115 individually synthesized and quality controlled xGen Lockdown Probes. The panel spans a 34 Mb target region (19,433 genes) of the human genome and covers 39 Mb of probe space, the genomic regions covered by probes. 
Source url: https://www.idtdna.com/pages/products/next-generation-sequencing/targeted-sequencing/hybridization-capture/predesigned-panels/xgen-exome-research-panel-v2

**Are there similar but not-quite-right values?**
Please list if applicable.

**Additional comments**

**Comment by allaway** [comment]
Closed by #78
