### ISSUE TITLE
Add [Illumina_NovaSeq_6000] to [platform]

### ISSUE THREAD

**Issue by jaybee84** [nf-osi/nf-metadata-dictionary#77]
**List the new value**
Value: `Illumina_NovaSeq_6000`

**Provide definition and source for the new value**
Definition:
Source url: https://www.illumina.com/systems/sequencing-platforms/novaseq.html

**Are there similar but not-quite-right values?**
Please list if applicable.

**Additional comments**

**Comment by allaway** [comment]
Closed by #78
