### ISSUE TITLE
Add [True_seq standard total RNA library kit] to [libraryPreparationMethod]

### ISSUE THREAD

**Issue by jaybee84** [nf-osi/nf-metadata-dictionary#80]
**List the new value**
Value: `True_seq standard total RNA library kit`

**Provide definition and source for the new value**
Definition: A robust, highly scalable whole-transcriptome analysis (RNA-Seq) solution for a variety of species and sample types, including human, mouse, and formalin-fixed, paraffin-embedded (FFPE) tissue.
Source url:https://www.illumina.com/products/by-type/sequencing-kits/library-prep-kits/truseq-stranded-total-rna.html

**Comment by anngvu** [comment]
Added as `TruSeq stranded total rna kit` (spelling) to correspond with [product page](https://www.illumina.com/products/by-type/sequencing-kits/library-prep-kits/truseq-stranded-total-rna.html). Note that generic `TruSeq` term seems to already exist, but there are several TruSeq kits and it could be justified to have more specific term.
