### ISSUE TITLE
Add [fr-firststrand] to [readPairOrientation]

### ISSUE THREAD

**Issue by jaybee84** [nf-osi/nf-metadata-dictionary#81]
**List the new value**
Value: `fr-firststrand`

**Provide definition and source for the new value**
Definition: Reads from the left-most end of the fragment (in transcript coordinates) map to the transcript strand, and the right-most end maps to the opposite strand. But we enforce the rule that the right-most end of the fragment (in transcript coordinates) is the first sequenced (or only sequenced for single-end reads). Equivalently, it is assumed that only the strand generated during first strand synthesis is sequenced.
Source url: https://chipster.csc.fi/manual/library-type-summary.html, http://onetipperday.sterding.com/2012/07/how-to-tell-which-library-type-to-use.html

**Comment by allaway** [comment]
Resolved by #83
