### ISSUE TITLE
Add [2D-Incucyte assay, a 2D-cell titer glo assay, a 3D microtissue assay, in vivo PDX assay] to [assay]

### ISSUE THREAD

**Issue by jaybee84** [nf-osi/nf-metadata-dictionary#82]
**List the new value**
Value: `2D-Incucyte assay, a 2D-cell titer glo assay, a 3D microtissue assay, in vivo PDX assay`

Using [OLS](https://www.ebi.ac.uk/ols/index) or a similar resource, please find a standard term that fits your needs. OLS-listed NCIT and OBI dictionaries are preferred sources. Non-OLS sources of ground truth for specific items such as ONCOTREE for cancer types, or GEO for platform definitions are also appropriate. 

**Provide definition and source for the new value**
Definition:
Source url:

**Are there similar but not-quite-right values?**
Please list if applicable.

**Additional comments**

**Comment by allaway** [comment]
Resolved by #83
