### ISSUE TITLE
Remove "bundle" being used for `resourceType`

### ISSUE THREAD

**Issue by anngvu** [nf-osi/nf-metadata-dictionary#93]
In reviewing data for mapping, found that "bundle", which is currently not defined in our schema (i.e. not a valid value) for `resourceType` is being used [here](https://www.synapse.org/#!Synapse:syn11614200/tables/query/eyJzcWwiOiJTRUxFQ1QgKiBGUk9NIHN5bjExNjE0MjAwIHdoZXJlIHJlc291cmNlVHlwZSA9ICdidW5kbGUnIiwgImFkZGl0aW9uYWxGaWx0ZXJzIjpbXSwgImluY2x1ZGVFbnRpdHlFdGFnIjp0cnVlLCAib2Zmc2V0IjowLCAibGltaXQiOjI1LCAic29ydCI6W119).

Options:
1. Should we add `bundle` and allow it to be used?
2. Change `bundle` annotation to `result` or `experimentalData`. (This is a zip file that might need inspection to reassign correct annotation.)

**Comment by allaway** [comment]
These annotations were added to capture the concept of a "dataset" (I can't recall why we settled on the word "bundle"...). I think tomorrow's conversation with Duminda will help us make a decision here, but I think we should probably plan to remove this annotation, and in fact remove these zipped datasets entirely (or at least "archive" them), and transition to bonafide "datasets" powered by views.
